### ISSUE TITLE
Localtuya is gone from integrations

### ISSUE THREAD

**Issue by ranrinc** [rospogrigio/localtuya#104]
please remove this post.. its my mistake.. did not wait for hacs to complete loading

**Comment by drinfernoo** [comment]
I do not have the ability to add localtuya in the integrations section... even after downgrading to 3.0.1 as suggested in other issues 🤔

**Comment by ranrinc** [comment]
> I do not have the ability to add localtuya in the integrations section... even after downgrading to 3.0.1 as suggested in other issues 🤔

Did you put the right folder inside custom_components
