### ISSUE TITLE
Garage Door open by itself

### ISSUE THREAD

**Issue by jforestd** [rospogrigio/localtuya#1051]
Hi!

I think the new update created a bug somewhere. My garage door automatically open at 3am this morning! I look in HA logg and it seams like the devise was unavailable for a fraction of second, and the I assume the system tought it was open, so he try to close it by itself.

I was quite afraid!

Thanks,

**Comment by sss2400** [comment]
Same problem w/ Garage door!

**Comment by SmileyZomb** [comment]
My circuit breaker shutdown randomly after update, my light too

**Comment by remlei** [comment]
probably related to #1019 again

I suggest downgrading to v4.0.0 if you want a workaround for this issue.

**Comment by jeremysherriff** [comment]
It is normal for the tuya devices to appear to be offline briefly (showing as `unavailable`). The state normally corrects within 5 seconds, sometimes a little longer but usually very quickly.  The correct action you should take is to set your automation to look for a specific `from` and `to` state, or to not take action if the previous state was `unavailable` using a `template` condition like this:
```
condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'unavailable' }}"
```

I can confirm that this situation is normal for older localtuya (e.g. 3.x) and also for many other integrations - the `unavailable` state can happen during HA start-up, during local network disruption, and where there are limitations on the number of connected clients (as is often the case with tuya devices).

**Comment by Aldaran** [comment]
> It is normal for the tuya devices to appear to be offline briefly (showing as `unavailable`). The state normally corrects within 5 seconds, sometimes a little longer but usually very quickly. The correct action you should take is to set your automation to look for a specific `from` and `to` state, or to not take action if the previous state was `unavailable` using a `template` condition like this:
> 
> ```
> condition:
>   - condition: template
>     value_template: "{{ trigger.from_state.state != 'unavailable' }}"
> ```
> 
> I can confirm that this situation is normal for older localtuya (e.g. 3.x) and also for many other integrations - the `unavailable` state can happen during HA start-up, during local network disruption, and where there are limitations on the number of connected clients (as is often the case with tuya devices).

Here the problem is not due to automation (like mine), I use a wifi meter to get 'total energy', the built-in relay is a side 'evil'.  And I don't have any automation that uses this switch, the only one is just added via DP.  Your example doesn't matter at all...

**Comment by jeremysherriff** [comment]
@Aldaran, my response is in regards to the issue raised by OP, regarding the garage door opening during the night after the switch has changed state unexpectedly.  Your issue is unrelated, and is to do with the default state of specific DPs during the start-up of the integration.  You should open your own issue.

**Comment by remlei** [comment]
> @Aldaran, my response is in regards to the issue raised by OP, regarding the garage door opening during the night after the switch has changed state unexpectedly. Your issue is unrelated, and is to do with the default state of specific DPs during the start-up of the integration. You should open your own issue.

im pretty sure it has nothing to do with HA last state as well so your post is probably offtopic or rather unrelated.

in short it has something related regarding 4.1.0 update with added DPS RESET functionality.  which causes device to act weird, eg, lights turning on randomly, fans turning off randomly, smartplugs/smart power strip turning off randomly, etc...

this bug only recently surfaced and not present on older versions.

heck I can actually reproduce this bug by just simulating a unavailable even on tuya device (a simple DEAUTH on the device is more than enough) and I can consistently trigger the device ON or OFF when it gets reconnected., so if the device is ON, it will turn off, if the device is off, it will turn on, if the device is passive, it will always follow its default state.

**Comment by jforestd** [comment]
To ve honest I just wanted to rise the defect 😅 My gf was so piss that I decided to try normal tuya. Back in the days I went with local tuya since garage dooor were a mess in the original integration. TY for the answer. I think as remlei mention it is related to issue #1019.
