### ISSUE TITLE
Unknown State of Cover/Shutters

### ISSUE THREAD

**Issue by cataseven** [rospogrigio/localtuya#1108]
If you don't want to see the state of partially opened cover as Unknown, just change the lines 111 and 117 in Cover.py file of Local Tuya Integration to "False".

After that you will it as Open XX%. ie Open 42%

![2022-10-29 23_25_40-Studio Code Server – Home Assistant](https://user-images.githubusercontent.com/52464808/198851406-5825d128-1e74-4c2b-b197-e009be398941.png)

https://github.com/piitaya/lovelace-mushroom/issues/794#issuecomment-1295964828

**Comment by patrik-malina** [comment]
@rospogrigio please integrate this fix. I have two shutters and can confirm this works as should.
Without this fix, shutters are reporting unavailable when not operating.

**Comment by rospogrigio** [comment]
OK pushed in master, will publish it with the next release.
