### ISSUE TITLE
Zigbee gateway support

### ISSUE THREAD

**Issue by vanek-865** [rospogrigio/localtuya#1120]
Hello, could you tell me if there was a merge with the [branch](https://github.com/rospogrigio/localtuya/pull/628)?
I couldn't add zigbee devices, after manually adjusting the files I got it.
The only thing for me is that it stopped finding devices automatically, but this is not critical, the main thing is that zigbee devices work locally.
If there was no merge because the files are different, can it be done?

**Comment by 1060778506** [comment]
Agree Agree to merge

**Comment by muertocaloh** [comment]
Interested on this functionality

**Comment by Sendery** [comment]
Also interested

**Comment by nhailong** [comment]
Hope merge will happen soon

**Comment by darth-aragoth** [comment]
I'm also interrested in this functionality.

**Comment by atlantden** [comment]
https://github.com/leeyuentuen/localtuya/
or it can be merged with this

**Comment by gian72** [comment]
> , after manually adjusting the files

Hi @vanek-865 could you please tell me where are conf files to adjust?

**Comment by vanek-865** [comment]
> Hi @vanek-865 could you please tell me where are conf files to adjust?

Hi,
https://github.com/rospogrigio/localtuya/pull/628/files

![image](https://user-images.githubusercontent.com/6773715/208425630-791dd6bf-410f-4cd7-9b09-abcd303ffa1c.png)

**Comment by OG-algo** [comment]
interested as well :)

**Comment by rospogrigio** [comment]
Sorry, I didn't notice the fork. I have introduced Zigbee support in PR #1493,  if anybody wants to test it and provide feedback, please comment in the PR.
