### ISSUE TITLE
Yaml Configuration

### ISSUE THREAD

**Issue by justus-go** [rospogrigio/localtuya#1171]
Can you please bring back Yaml configuration. It would make the configuring of multiple divices so much easier. ;)

~justus

**Comment by ThomasCr** [comment]
+1
I also cant see any comport in the gui right now. It makes things more complicated.
every time you need to change on DP, all DPs need to redefined.

It is also not possible to delete on device - because we only have: 
*Add a new device
*Edit a device
*Reconfigure Cloud API account

**Comment by apbarratt** [comment]
I have to agree with this.  The GUI is very rough around the edges and its flow makes mistakes exceptionally easy, especially with the requirement to do everything as one long chain.  If I find some time, I'd very much like to lend some effort into improving the UI but in the mean time I have found myself editing the yaml directly on the `/config/.storage/core.config_entries` file to repair things, which is something that I would far rather avoid doing as it's such a dangerous area to be editing directly.

**Comment by rospogrigio** [comment]
Not going to happen, sorry. It is too painful to maintain codes both for YAML (which is being abandoned by almost all the Integrations) and config flow. We can try to improve the config flow if there are some problems but I'm not willing to restore YAML configuration.
@ThomasCr : it is possible to delete a device: enter it under Devices -> 3 dots in the Device Info frame -> Delete.

**Comment by 1RandomDev** [comment]
Did you guys find anyone that maintains an active fork which reimplements the YAML config again?

**Comment by psychowood** [comment]
> Not going to happen, sorry. It is too painful to maintain codes both for YAML (which is being abandoned by almost all the Integrations) and config flow. We can try to improve the config flow if there are some problems but I'm not willing to restore YAML configuration.
> @ThomasCr : it is possible to delete a device: enter it under Devices -> 3 dots in the Device Info frame -> Delete.

What about allowing to copy/paste in a textarea something (yaml, json, whatever format you decide that does not require to maintain two different implementations) that could bypass the UI when configuring a device, just after inputing deviceid/key/ip ?

That would also make quite easy to share device templates between users, which imho is possibly the only real weak point of this great project.

**Comment by rospogrigio** [comment]
Well, that's a nice idea but again, then we'd need to maintan the code that parses that text but I'll think about it. Maybe something like exporting/importing directly the entities json from core.config_entries, so that the users can share it... I'll give it a thought, but not in the short period, sorry.
