### ISSUE TITLE
Need help for HVAC setup

### ISSUE THREAD

**Issue by carmelo42** [rospogrigio/localtuya#1186]
Hello, I'm trying to use localtuya with my HVAC air/air cooling/warming air conditioning system.
I have theses DPs : 

<img width="321" alt="Capture d’écran 2022-12-20 à 09 31 20" src="https://user-images.githubusercontent.com/2070041/208620048-1ad58cd8-c948-44e8-b1c3-ac05bef98266.png">

<img width="316" alt="Capture d’écran 2022-12-20 à 09 31 28" src="https://user-images.githubusercontent.com/2070041/208620073-5f9e013b-7e48-4b86-ad2a-7d1c8b554f51.png">

I can't figure what I have to put for "HVAC Mode DP (optional)" and "HVAC Current Action DP (optional)

I can change the target temparture, but can't turn off or on the system.

**Comment by behtjes** [comment]
It depends on what values you get when you switch on or off your device. Mostly true or false.
Try DP 4 for both (it looks like value 'hot' means a HVAC mode (like hot, cool, etc). 
Set HVAC Current Action Set (optional) to True/False

You may have to edit climate.py to add your modes to make different modes to work.

**Comment by carmelo42** [comment]
It's now working for Airton - Yuzu - Fujicool HVAC devices (self installables HVAC devices). 
I've forked the repo and added my modifications : https://github.com/carmelo42/localtuya/tree/fujicool-yuzu-hvac

**Comment by tomadam123** [comment]
Whether you're installing a new system or need assistance with an existing setup, feel free to ask any questions you have or provide more details about what you need help with. Whether it's selecting the right equipment, understanding installation procedures, optimizing efficiency, or troubleshooting issues, I'm here to assist you every step of the way. [Get More Info](https://atlantic-heatingcooling.com/)
