### ISSUE TITLE
LocalTuya config file location

### ISSUE THREAD

**Issue by tevas007** [rospogrigio/localtuya#1207]
i can't find where is LocalTuya config files are located (with my devices names. etc.). Can anybody tell me ?

**Comment by Segran** [comment]
Same here... trying to remove 2 devices but no luck.

**Comment by apbarratt** [comment]
It's all hidden away in the big scary home assistant entities file that isn't really meant to be touched by hand.
I've been able to fix things by altering localtuya entities there but I seem to recall I had to always run a restart of home assistant and in many cases I had to rerun through the "edit device" stuff in localtuya for my changes to actually become active.  But it is doable and once I got it working it made the world of difference.  I'd say it made a major case for me to bringing back to yaml configurable method the old version of this integration used to provide us.

`/config/.storage/core.config_entries` is the file you are looking for.

**Comment by nicknol** [comment]
@apbarratt Thanks a lot for the file and its location.

@all please be carefull, mistakes in the file would prevent HA to start, and on a Raspberry PI you've hardly any chance to fix it since you can't access the file anymore through file editor.
=> take backups!

**Comment by Segran** [comment]
Thanks, after som house cleaning of that file my log is only a fraction  in size….

Skickat från min iPad

**Comment by tevas007** [comment]
Thank you !
