### ISSUE TITLE
Support for KLK Ceiling Fan + Light Combo

### ISSUE THREAD

**Issue by jonatino** [rospogrigio/localtuya#1209]
Would be nice to have support for fan + light combo units. When configuring this plugin in home assisstant, it only imports 1 device with 1 entity. It should be 1 device with 2 entities (light + fan).

![image](https://user-images.githubusercontent.com/1808569/210277075-eb72b988-59af-4598-a118-a6c4632f0b4d.png)

Device info:
![image](https://user-images.githubusercontent.com/1808569/210277099-29f3c044-a7c5-4055-805f-0c8cbe47be98.png)

Debug info from tuya:
![image](https://user-images.githubusercontent.com/1808569/210277014-d4375ca5-b359-4d2c-980f-7fe6dd207d12.png)

**Comment by remlei** [comment]
you can add multiple entities with localtuya, just add them 1 by 1 and dont forget to uncheck the  **"Do not add any more entities"** until you finally added all enties you want to add for that single device.

**Comment by jonatino** [comment]
> you can add multiple entities with localtuya, just add them 1 by 1 and dont forget to uncheck the **"Do not add any more entities"** until you finally added all enties you want to add for that single device.

Yes you can add multiple entities, but this integration does not support combo units.

**Comment by remlei** [comment]
> Yes you can add multiple entities, but this integration does not support combo units.

I cant really understand what your saying, I also had 4 of this tuya based fan and light controller, 2 of each are different model, two of them is fan+light but no light dim support, and the last two ones have fan+light with dimming support. 

all of it I can easily add all of those entities with localtuya on a single device, no issues.

If this device is one of those niche category, what I would recommend is donate that device to the developer and see what he can do with it.

**Comment by sou7611** [comment]
I can't get this to work either.  Same device, KLK Ceiling Fan.

I can control the fan itself, but not the light.
