### ISSUE TITLE
Manual DPS settings

### ISSUE THREAD

**Issue by jlhall87** [rospogrigio/localtuya#1224]
I have 14 LED lights, 13 of which have connected ok. I am unable to get the final one to connect and get the error Connection to device succeeded but no datapoints found.

All devices are running the same module 3.3

In the log im seeing error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 6: invalid start byte
2023-01-09 23:13:35.503 ERROR (MainThread) [custom_components.localtuya.pytuya] [350...d11] Failed to get status: 'utf-8' codec can't decode byte 0xa8 in position 6: invalid start byte

I know the required DPS and Values but when i add the DPS manually the value defaults to -1

**Comment by rospogrigio** [comment]
This is a known but unexplained issue. Try to re-pair it with the app, I fixed it this way when it happened to me.
