### ISSUE TITLE
orange border around integration

### ISSUE THREAD

**Issue by bkbartk** [rospogrigio/localtuya#1248]
## Environment
Whenever I edit a device the integration gets an orange border in HA and stops working
![image](https://user-images.githubusercontent.com/17070805/213007141-b66c6811-57b5-4558-8c04-93ecbdaf5ea8.png)
the reload button disappears and I need to restart HA to fix this.
- Localtuya version: HACS v5.0.0 
- Home Assistant Core version: Home Assistant 2023.1.5
- [x] Does the device work using the Home Assistant Tuya Cloud component ? 

## Steps to reproduce
In HA go to integrations
click configure on localtuya tile
Select "Edit a device"
Submit, select 1, submit, submit
modify some "status" values and click submi

## Provide Home Assistant traceback/logs
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/localtuya/common.py:273
Integration: LocalTuya (documentation, issues)
First occurred: 21:34:32 (1 occurrences)
Last logged: 21:34:32

Error unloading entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 311, in async_unload_entry
    await device.close()
  File "/config/custom_components/localtuya/common.py", line 308, in close
    await self._connect_task
  File "/config/custom_components/localtuya/common.py", line 273, in _make_connection
    and self._dev_config_entry[CONF_SCAN_INTERVAL] > 0
TypeError: '>' not supported between instances of 'str' and 'int'

-->
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/localtuya/common.py:273
Integration: LocalTuya (documentation, issues)
First occurred: 21:34:32 (1 occurrences)
Last logged: 21:34:32

Error unloading entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 311, in async_unload_entry
    await device.close()
  File "/config/custom_components/localtuya/common.py", line 308, in close
    await self._connect_task
  File "/config/custom_components/localtuya/common.py", line 273, in _make_connection
    and self._dev_config_entry[CONF_SCAN_INTERVAL] > 0
TypeError: '>' not supported between instances of 'str' and 'int'

``

**Comment by plandregan** [comment]
I am also seeing this with 5.0.0. Just added a new device, and the Integration went orange and stopped. A restart of the HA and its back with the new one added. 3.3 device.
Also see periodic others become unavailable aswell, these are 3.4 devices.
I have a mix of 3.3 and 3.4 devices.

**Comment by viv-design** [comment]
I'm experiencing the same problems as @plandregan - v5.0.0

**Comment by plandregan** [comment]
Upgrade to beta 5.1.0beta0

**Comment by kmanan** [comment]
I'm having this issue with the Govee integration. Any ideas on what this means?
