### ISSUE TITLE
Adding ZX-5012 BT relay and NX-4964 Key Box

### ISSUE THREAD

**Issue by klona** [rospogrigio/localtuya#1254]
Hi, trying to add a keybox  https://www.amazon.fr/Coffret-cl%C3%A9s-connect%C3%A9-%C3%A9tanche-XCase/dp/B08WWQ5CG2
This box is BT only, so i get a BT relay ZX-5012  https://www.pearl.fr/article/ZX5012/passerelle-reseau-mesh-pour-appareils-connectes-compatibles-elesion 

Configured on Tuya Smart and working.
Created Project  and get ID & local keys
Local tuya installed , linked to cloud, and automatically detect ZX-5012 and fill local key (same one I get from developer.tuya !)

Adding and got en error : "Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists."

Any help is welcome as I dont know what to do..
Thanks in advance,
/klona

Logs I got :

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:450
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 7:59:19 PM (2 occurrences)
Last logged: 7:59:27 PM

[bf2...fhx] Failed to get status:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 857, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 789, in status
    status = await self.exchange(DP_QUERY)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 784, in exchange
    return await self.exchange(command, dps)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 763, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

System info :

    "installation_type": "Home Assistant OS",
    "version": "2023.1.5",

    "python_version": "3.10.7",

    "os_version": "5.15.80",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",

    "localtuya": {
      "version": "5.0.0",
...
 "data": {
    "region": "eu",
    "username": "localtuya",
    "no_cloud": false,
    "user_id": "eu1...p9x",
    "client_id": "pux...ddy",
....
        "name": "NX-4964",

**Comment by klona** [comment]
Hi, please tell me if my question is silly, if there is not enough info or..
I would really to make it work but have no clue for next step

Thanks.

**Comment by klona** [comment]
Hi, last try to get some help. I really dont konw how to go to next step..

`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.3.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.03.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "livebox": {
      "version": "1.8.5",
      "requirements": [
        "aiosysbus==0.2.1"
      ]
    },
    "hacs": {
      "version": "1.31.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "localtuya": {
      "version": "5.0.0",
      "requirements": []
    },
    "myEnedis": {
      "version": "2.3.1",
      "requirements": [
        "packaging>=20.8"
      ]
    }
  },
  "integration_manifest": {
    "domain": "localtuya",
    "name": "LocalTuya integration",
    "version": "5.0.0",
    "documentation": "https://github.com/rospogrigio/localtuya/",
    "dependencies": [],
    "codeowners": [
      "@rospogrigio",
      "@postlund"
    ],
    "issue_tracker": "https://github.com/rospogrigio/localtuya/issues",
    "requirements": [],
    "config_flow": true,
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "region": "eu",
    "username": "localtuya",
    "no_cloud": false,
    "user_id": "eu1...p9x",
    "client_id": "pux...ddy",
    "client_secret": "4b3...1c5",
    "devices": {},
    "cloud_devices": {
      "bf2cab32bc22041fc3dfhx": {
        "active_time": 1673973284,
        "biz_type": 0,
        "category": "wg2",
        "create_time": 1672947885,
        "icon": "smart/icon/ay1525342462043yjwZs/1654843051a06b6c7fc2a.png",
        "id": "bf2cab32bc22041fc3dfhx",
        "ip": "86.216.158.215",
        "lat": "43.5291",
        "local_key": "53f...c03",
        "lon": "5.4454",
        "model": "Bluetooth-Gateway",
        "name": "Relais BT",
        "online": true,
        "owner_id": "34830789",
        "product_id": "qg4jkqwe",
        "product_name": "ZX-5012",
        "status": [],
        "sub": true,
        "time_zone": "+01:00",
        "uid": "eu1627567764077XMp9x",
        "update_time": 1676804008,
        "uuid": "02e5aeb41b3be351"
      },
      "bf2e03npfqaeskqg": {
        "active_time": 1673973414,
        "biz_type": 0,
        "category": "jtmspro",
        "create_time": 1673973414,
        "icon": "smart/icon/ay1574387149429focnK/c9c7030303f490d5f5338414061c1876.jpg",
        "id": "bf2e03npfqaeskqg",
        "ip": "",
        "lat": "43.5291",
        "local_key": "53f...c03",
        "lon": "5.4454",
        "model": "SMKB2_ty_03_pro",
        "name": "Bo\u00eete Cl\u00e9s",
        "node_id": "e15dd321b187b186",
        "online": true,
        "owner_id": "34830789",
        "product_id": "qicggi0m",
        "product_name": "NX-4964",
        "status": [
          {
            "code": "unlock_method_create",
            "value": "Af8AAwQAAA=="
          },
          {
            "code": "unlock_method_delete",
            "value": ""
          },
          {
            "code": "unlock_method_modify",
            "value": ""
          },
          {
            "code": "residual_electricity",
            "value": 100
          },
          {
            "code": "battery_state",
            "value": "high"
          },
          {
            "code": "unlock_password",
            "value": 4
          },
          {
            "code": "unlock_dynamic",
            "value": 0
          },
          {
            "code": "unlock_ble",
            "value": 1
          },
          {
            "code": "alarm_lock",
            "value": "wrong_finger"
          },
          {
            "code": "temporary_password_creat",
            "value": ""
          },
          {
            "code": "temporary_password_delete",
            "value": ""
          },
          {
            "code": "temporary_password_modify",
            "value": ""
          },
          {
            "code": "synch_method",
            "value": "AQE="
          },
          {
            "code": "unlock_temporary",
            "value": 0
          },
          {
            "code": "remote_no_dp_key",
            "value": "AAAB"
          },
          {
            "code": "unlock_phone_remote",
            "value": 256
          },
          {
            "code": "unlock_voice_remote",
            "value": 0
          },
          {
            "code": "password_offline_time",
            "value": "1673973414"
          },
          {
            "code": "unlock_offline_clear_single",
            "value": ""
          },
          {
            "code": "unlock_offline_clear",
            "value": ""
          },
          {
            "code": "unlock_offline_pd",
            "value": "v84Ruc83JSeLPmBZfaxtsg=="
          },
          {
            "code": "record",
            "value": "//8AATk2Mjc1NjA3AA=="
          },
          {
            "code": "check_code_set",
            "value": "AAH//wAAAAAAAAAAAP//AA=="
          },
          {
            "code": "ble_unlock_check",
            "value": "AAH//zk2Mjc1NjA3AWPG0HUAAA=="
          },
          {
            "code": "unlock_record_check",
            "value": ""
          },
          {
            "code": "remote_pd_setkey_check",
            "value": "AAH//zk2Mjc1NjA3AQABAA=="
          }
        ],
        "sub": true,
        "time_zone": "+01:00",
        "uid": "eu1627567764077XMp9x",
        "update_time": 1676803986,
        "uuid": "e15dd321b187b186"
      }
    }
  }
}`

**Comment by rospogrigio** [comment]
Gateways are not supported yet, sorry, maybe in the future...

**Comment by klona** [comment]
Thx man for your reply.
Devices are working great but I get an "unsupported Device" in Home assistant using Tuya, so LocalTuya was my only chance.
Stucked with the tuya smartphone app, and no link possible wih HA.

If one day you put it on list, I would be pleased to participate as sponsor for equipment or money to help on project, as i am unable to help on code part.


Regards,
Klona

**Comment by KevinCluse** [comment]
Possible now? Any updates?
I need the same Product. xcase.
