### ISSUE TITLE
Integration not found (0.117)

### ISSUE THREAD

**Issue by phk-r** [rospogrigio/localtuya#126]
Hi!
Seems like the update of Home assistant to 0.117 broke the integration some how. 
I've installed via HACS and it was working up until I updated HA today. The integrations page doesn't seem to find localtuya anymore.  I have tried reinstalling via HACS and rebooting HA, but no difference.

Got this in the log:
```
Logger: homeassistant.setup
Source: setup.py:138
First occurred: 11:36:18 AM (1 occurrences)
Last logged: 11:36:18 AM
Setup failed for localtuya: Integration not found. 
```

Let me know if I can provide any more information to resolve the issue. 
Best regards,
phkr

**Comment by postlund** [comment]
I run 0.117 as well and it works fine. Make sure you don't upgrade to 3.0.3 though, stay on 3.0.1.

**Comment by phk-r** [comment]
> I run 0.117 as well and it works fine. Make sure you don't upgrade to 3.0.3 though, stay on 3.0.1.

Ah crap. Will give that a try. Thanks

**Comment by phk-r** [comment]
Seems like downgrading did the trick. Might be a good idea to remove 3.0.2 and 3.0.3 if they aren't working fully? =)

**Comment by AjaxOdessa** [comment]
Have this problem with HA 2021.10.6 and localtuya of the latest version in the repo. Should I rollback to 3.0.1 too?
