### ISSUE TITLE
Light entity is unavailable

### ISSUE THREAD

**Issue by Marc1200** [rospogrigio/localtuya#1262]
Hello, 

I have a problem with the local tuya integration when i add a light entity it says unavailable
![Schermafbeelding 2023-01-23 214220](https://user-images.githubusercontent.com/68737063/214145802-ab4869fe-57cf-4999-a30a-e150ca98af4e.png)
i can find the light in the normal tuya integration and control the brightness and colortemp. 
i Also can find it when i add the tuya light in the localtuya integration as a switch then i could control the light but not the brightness and colortemp.
the product is: LSC SMART Connect A60 gold CCT
this are the options of my light:
![1](https://user-images.githubusercontent.com/68737063/214146336-9a4b34d6-e6b1-4910-943f-ea745874723a.png)
![2](https://user-images.githubusercontent.com/68737063/214146342-9f420b05-7d86-47ff-9e11-4d760e29469e.png)
![3](https://user-images.githubusercontent.com/68737063/214146431-fbc988a9-cdf0-4ca7-a822-37a346d05faa.png)

**Comment by skoglar** [comment]
Hey, I was just struggling with this for another model, its just a matter of finding the [right DPs for that model](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump). You can get `tuyadebug` and run it using the device id you get from localtuya when trying to add the new lightbulb

![image](https://user-images.githubusercontent.com/46354669/214466310-3e79f009-1d8b-4e6f-81c4-cd231fb2c9c6.png)

Then if you're on linux you could just `watch` the script with something like 
```shell
watch -n 1 'python test.py myid 192.168.1.95 mylocalkey'
```
and see what DPs change value when you change **brightness**, **color**, etc from the android app.

**Comment by Istria1704** [comment]
I have the same "Action" LSC light. They also often go unavailable. Have not found a solution yet. I will try to flash them to Tasmota when I get the chance. They are old, so I'm hoping they are still esp8266-based. 

What I did notice, is that they come back online when I turn them on and off again using the Tuya app. But it only helps for a short time. After a while, they go unavailable again.

**Comment by Marc1200** [comment]
i now use the Tuya Local integration from @make-all, it works a bit better, but for "Action" light i cannot change color temperature, only brightness.
