### ISSUE TITLE
Local API without HASS? 

### ISSUE THREAD

**Issue by elockman** [rospogrigio/localtuya#1264]
Hello,

I'm adding an issue because there is no discussion tab.

I would like to connect to a Tuya thermostat (PCT513-WB-TY) locally without Home Assistant. Does Local Tuya provide a local API to read a thermostat with curl statements, or something similar?

The Tuya developer site allows you to query devices, but it hits the "https://openapi.tuyaus.com/v1.0/iot-03/devices/{deviceID}/functions" site. Does Tuya Local allow something similar with the device IP address, even if it is a more mechanical process?

**Comment by elockman** [comment]
I would be happy with just reading the status at this point. In the cloud it looks like this:

curl --request GET "https://openapi.tuyaus.com/v1.0/iot-03/devices/{deviceID}/status" --header "sign_method: HMAC-SHA256" --header "client_id: **{clientID}**" --header "t: 1674835464167" --header "mode: cors" --header "Content-Type: application/json" --header "sign: **{signature}**" --header "access_token: **{token}**" 

Is there an equivalent call to the device locally?

Thanks.

**Comment by rospogrigio** [comment]
No, sorry.
