### ISSUE TITLE
looses connection to bulb after every ha restart

### ISSUE THREAD

**Issue by FaserF** [rospogrigio/localtuya#128]
First, thanks for the integration.
When I have set it up, it works great, unfortunatly after every ha restart this integration seems to loose the connection, as the bulb gets unavailable. I then have to remove it and add it again, then it works fine.

**Comment by postlund** [comment]
That sounds like a bug. Please enable logging and attach logs here after doing a restart (when the bulb is unavailable).

https://github.com/rospogrigio/localtuya#debugging

**Comment by FaserF** [comment]
After removing the whole integration and adding it back again it seems to work better. Sorry for the useless bug report

**Comment by postlund** [comment]
Maybe it was a temporary hiccup. If it happens again, just open a new issue and attach logs 👍
