### ISSUE TITLE
Energy monitor not working with Wiby smart plug

### ISSUE THREAD

**Issue by alexander1602** [rospogrigio/localtuya#1310]
## The problem
The energy monitor not working with Wiby smart plug

## Environment

- Localtuya version: 5.0.0
- Home Assistant Core version: Home Assistant 2023.2.5
- [] Does the device work using the Home Assistant Tuya Cloud component ? x
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ? smart life

## Steps to reproduce

add the device thought the setup and energy monitor doesn't show up. i can just see the entity to turn the light on but not the values of the consumption.

## Additional information
I can see the values of consumption on the app and on the configuration panel while doing the setup, but i can't see them later on the device tab. I just can turn the plug on and off but nothing more than this

![Screenshot 2023-02-28 at 16 44 39](https://user-images.githubusercontent.com/64891131/221904759-851da0c5-0547-424e-b18c-2494a7e8e9ce.png)
![Screenshot 2023-02-28 at 16 46 01](https://user-images.githubusercontent.com/64891131/221904767-0134336d-62a4-4be6-84b2-7a4b3f6b46b3.png)
![Screenshot 2023-02-28 at 16 44 22](https://user-images.githubusercontent.com/64891131/221904772-630d25ed-6414-4bb7-af03-21765afe8e20.png)
![Screenshot 2023-02-28 at 16 45 53](https://user-images.githubusercontent.com/64891131/221904778-71f03dd4-1a01-47eb-9948-4dbec78e1596.png)

**Comment by alexander1602** [comment]
I actually can see them in the attributes but why they doesn't show up ad entities?

**Comment by patrik-malina** [comment]
As I mentioned, when creating device, beside switch you need to add 3 more sensors (voltage, current and power) 
![Screenshot_20230228_192102_Home Assistant](https://user-images.githubusercontent.com/73561855/221944718-05dea552-602a-42ad-9acc-926286be3468.jpg)

**Comment by patrik-malina** [comment]
When adding new device after adding switch, UNCHECK Do not add more entities, select sensor and configure it. then similiar add two more.
Off course, you need first to delete device (localtuya -> device name -> tree dots right of download diagnostic

**Comment by alexander1602** [comment]
Okay perfect. Thank you so much, i appreciate. Works!
