### ISSUE TITLE
Integration reload fails with error

### ISSUE THREAD

**Issue by snigehere** [rospogrigio/localtuya#1315]
## The problem
Since installing the latest version of HA I am unable to use the integration reload function in settings> devices and services> localtuya> reload as it ends with an error.  The only recovery after that is a system reboot

Error details:
2023-03-05 06:38:34.797 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 311, in async_unload_entry
    await device.close()
  File "/config/custom_components/localtuya/common.py", line 308, in close
    await self._connect_task
  File "/config/custom_components/localtuya/common.py", line 273, in _make_connection
    and self._dev_config_entry[CONF_SCAN_INTERVAL] > 0
TypeError: '>' not supported between instances of 'str' and 'int'

I need to reload because I still face issues where devices go unavailable and do not recover.

## Environment

  "home_assistant": 
    "installation_type": "Home Assistant OS",
    "version": "2023.3.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.01.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "vm",
    "run_as_root": true
  "custom_components": 
    "hacs": 
      "version": "1.31.0",
      "requirements": ["aiogithubapi>=22.10.1"]
    "localtuya": 
      "version": "5.0.0",
      "requirements": []
	  
  "integration_manifest": 
    "domain": "localtuya",
    "name": "LocalTuya integration",
    "version": "5.0.0",
    "documentation": "https://github.com/rospogrigio/localtuya/",
    "dependencies": [],
    "codeowners": [
      "@rospogrigio",
      "@postlund"
    ],
    "issue_tracker": "https://github.com/rospogrigio/localtuya/issues",
    "requirements": [],
    "config_flow": true,
    "iot_class": "local_push",
    "is_built_in": false

- [x] Was the device working with earlier versions of localtuya ? Which one? 
- [x] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

Go to settings> devices and services> localtuya> reload

**Comment by rospogrigio** [comment]
Try the v5.1.0-beta0 version, it should fix this.

**Comment by snigehere** [comment]
Thanks for your work on this integration.. installed the beta and that solved the reliad issue
