### ISSUE TITLE
Smart Garage Door Opener stopped working

### ISSUE THREAD

**Issue by diemon24** [rospogrigio/localtuya#1317]
The problem
The two devices worked fine on my network. It may have stopped working after updating LocalTuya. I tried to pair the devices, give them new IP addresses, but they only work in the SmartLife application. They worked great for a long time and stopped working 2-3 weeks.

Smart Garage Door Opener: 
![IMG_0634](https://user-images.githubusercontent.com/91910101/222989769-4fd2a372-61d8-4e89-927b-f2a5ac2bce66.jpeg)

LocalTuya: 2023.3.0
Home Assistant 2023.3.1
Frontend 20230302.0 - latest

From iot Tuya Device Information: 

{
  "result": {
    "active_time": 1678052999,
    "biz_type": 18,
    "category": "ckmkzq",
    "create_time": 1678052999,
    "icon": "smart/icon/ay1525015673758Ghvpg/9bc68073d75ccabdd7345459c156b473.png",
    "id": "bfb918b23442a8ffade2v1",
    "ip": "-------",
    "lat": "-------",
    "local_key": "--------------",
    "lon": "------",
    "model": "",
    "name": "Garage",
    "online": true,
    "owner_id": "26538807",
    "product_id": "qiy5ayhzku1iqzsb",
    "product_name": "Smart Garage Door Opener",
    "status": [
      {
        "code": "switch_1",
        "value": false
      },
      {
        "code": "countdown_1",
        "value": 0
      },
      {
        "code": "doorcontact_state",
        "value": false
      },
      {
        "code": "tr_timecon",
        "value": 17
      },
      {
        "code": "countdown_alarm",
        "value": 0
      },
      {
        "code": "door_control_1",
        "value": "open"
      },
      {
        "code": "voice_control_1",
        "value": false
      },
      {
        "code": "door_state_1",
        "value": "none"
      }
    ],
    "sub": false,
    "time_zone": "------",
    "uid": "---------",
    "update_time": 1678053063,
    "uuid": "-------"
  },
  "success": true,
  "t": 1678054118363,
  "tid": "----------------"
}

Logger: homeassistant.util.logging
Source: util/logging.py:168 
First occurred: 01:30:32 (1 occurrences) 
Last logged: 01:30:32

Exception in _update_handler when dispatching 'localtuya_bfb918b23442a8ffade2v1': ({'1': False, '2': 0, '3': False, '4': 17, '5': 0, '12': 'none'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 408, in _update_handler self.status_updated() File "/config/custom_components/localtuya/cover.py", line 195, in status_updated if self._state.isupper(): AttributeError: 'bool' object has no attribute 'isupper'

<img width="764" alt="image" src="https://user-images.githubusercontent.com/91910101/222990112-da159aaf-69ce-4e32-84a6-a47c7c7757be.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/91910101/222990166-c66bbe65-b52d-4075-bc30-e32ddaa63be3.png">

**Comment by cataseven** [comment]
Setup like this

open_close_stop
position
2 (value:0)
2 (value:0)

**Comment by diemon24** [comment]
> Setup like this
> 
> open_close_stop position 2 (value:0) 2 (value:0)
> 
> If this doesnt work please share all options of Question 3 and 4

yes it works. Thx
