### ISSUE TITLE
Delete a device from many

### ISSUE THREAD

**Issue by epajfl00** [rospogrigio/localtuya#1353]
A silly question, but I can't seem to work out how to delete a device, I have 4 devices already defined and working, but now I want to remove 1 of them.
![image](https://user-images.githubusercontent.com/86779948/232407438-e23f9d88-6312-4f93-aeef-269a162bf527.png)

 The obvious way is to click the 3 dots and select delete, however this would delete Localtuya, so all 4 devices would be deleted. Is this the case?
![image](https://user-images.githubusercontent.com/86779948/232406560-f2ab7259-964f-4e33-b99c-b2d72d341f9a.png)

A better way would be in the config, have the option to delete the specific device. Is this possible?
![image](https://user-images.githubusercontent.com/86779948/232406980-d93ce332-d536-4b2a-a6fd-c5366f07fe15.png)

**Comment by remoteassist** [comment]
### Just open the device itself and delete.
![image](https://user-images.githubusercontent.com/115590002/233855161-30d878b2-1244-4673-9b98-c2c1cee79548.png)

**Comment by epajfl00** [comment]
Thank you, I had not noticed that delete was hidden there, much appreciated.
