### ISSUE TITLE
Zigbee devices in leeyuentuen's fork

### ISSUE THREAD

**Issue by darth-aragoth** [rospogrigio/localtuya#1378]
Hello,
in one of latest updates in leeyuentuen's fork (https://github.com/leeyuentuen/localtuya) there was added support for Zigbee / Bluetooth gateway and its subdevices. Will be possible to merge changes with this project?

**Comment by zeduperes** [comment]
+1 vote

**Comment by StudioRV** [comment]
+1 vote

**Comment by goodsale** [comment]
+1 Vote


 leeyuentuen's fork (https://github.com/leeyuentuen/localtuya)  still doesn't work properly with zigbee devices.
It can only check the status but not turn on/off (with switch).

It would be wonderful if the projects were unified
Thank you!

**Comment by Zannen0** [comment]
+1 vote

**Comment by danielnascimentocunha** [comment]
+1 vote

**Comment by viny182** [comment]
+ vote

Zigbee gateway support would be awesome!

**Comment by goodsale** [comment]
> 
leeyuentuen Localtuaya with a small patch now works with zigbee devices!

Please merge the projects! Thanks

**Comment by darth-aragoth** [comment]
What patch? I have latest version but I still can't control devices, I can only read their parameters.

**Comment by goodsale** [comment]
Simple modify the file /config/custom_components/localtuya/__init__.py adding the lines between  "#START - update from yakish777"  and  "#END - update from yakish777" and for me all works fine.

```
        elif PARAMETER_DATA in json_data:
            json_data[PARAMETER_DATA] = {PROPERTY_DPS: data}
            #START - update from yakish777 
            if cid is not None:
                json_data[PARAMETER_DATA][PARAMETER_CID] = cid
            #END - update from yakish777 
        else:
            json_data[PROPERTY_DPS] = data
``` 

You find all at this link: 

https://github.com/leeyuentuen/localtuya/issues/65

**Comment by viny182** [comment]
Hello,

I also confirm that the patch works, but the correct file to patch is actually **"/config/custom_components/localtuya/pytuya/__init__.py"**, considering you are using the release *"3.7.0 Beta 10"**
 
You should add only the lines below after line 1378: 

```
                #START - update from yakish777 
                if cid is not None:
                    json_data[PARAMETER_DATA][PARAMETER_CID] = cid
                #END - update from yakish777 
```
Here is a screenshot on how it should look like:
![image](https://github.com/rospogrigio/localtuya/assets/65199912/bae67aaa-8530-4c5e-9abc-63775ea0d579)

**Comment by viny182** [comment]
a new beta version was released with the patch above... just update to https://github.com/leeyuentuen/localtuya/tree/3.7.0-beta.11 and you will not  be required to change any files manually...

**Comment by goodsale** [comment]
now beta 12 👍

**Comment by darth-aragoth** [comment]
Thank you guys, I'll check it ASAP. Is there any chance to fix problems with cover controllers with time-based positioning in that fork described #[here](https://github.com/leeyuentuen/localtuya/issues/59)?

**Comment by darth-aragoth** [comment]
Works great, thank you :) The question remains whether something can be done with cover controllers.

**Comment by rospogrigio** [comment]
Sorry, I didn't notice the fork. I have introduced Zigbee support in PR #1493,  if anybody wants to test it and provide feedback, please comment in the PR.
