### ISSUE TITLE
local key doesn't seem to work anymore

### ISSUE THREAD

**Issue by johnnykang** [rospogrigio/localtuya#1380]
Hi,

I notice the key has different format for the devices that have been reactivated via SmartLife app. and the key doesn't seem to work with LocalTuya anymore.

The key format now contains special character while the old key format was just a-f0-9. 

`could not decrypt data: wrong local_key?`

that's the exception i am getting.

I retrieved the key via the tinytuya or using the Cloud API integration, no go. 

any thought?

**Comment by theneo93** [comment]
I have same error. Analising the localtuya key in iot.tuya.com the key is same get in localtuya integration.

**Comment by johnnykang** [comment]
I managed to resolve the issue. 

You can refer to https://github.com/jasonacox/tinytuya/discussions/341#discussioncomment-5835758 .

**Comment by brandon-meadows** [comment]
Why is this a closed issue? It's still an issue in localtuya is there an update that fixes this?

**Comment by johnnykang** [comment]
this PR will address the root cause - https://github.com/rospogrigio/localtuya/pull/1381
