### ISSUE TITLE
Dummy energy meter for light bulbs!

### ISSUE THREAD

**Issue by SmartM-ui** [rospogrigio/localtuya#142]
Hi @postlund @ultratoto14,
would it be possible to integrate an energy meter for light bulbs?
We have in the state of the bulbs the max value "brightness: 255".
Knowing that the brightness value 0 corresponds to the value 1.5W (standby consumption of the wifi) and the brightness 255 corresponds to a consumption of 7.5W (for my bulb), could we implement an indicator of W currently used?
It would be great if you could indicate the maximum wattage of the bulb through the yaml.
Don't hate me for ideas that involve your work -)

**Comment by ultratoto14** [comment]
Hi @SmartM-ui, thanks for the idea. I don't think this is the purpose of this integration.
It is easily done using a template sensor in HA.
Also, the consumption is not linearly linked to the brightness

**Comment by postlund** [comment]
I was just about to write exactly what @ultratoto14 just wrote. You can do that with a template sensor. But just an estimate unless you provide a function that can calculate the amount of power used by the light (as stated, just looking brightness is not accurate way to calculate power consumption).

**Comment by SmartM-ui** [comment]
@ultratoto14 @postlund 
But I meant a fictitious non-real energy meter!
However I agree with you that it is better to create a sensor on Home Assistant. I was already studying how to process it.
Instead, I remain of the idea that greater brightness inevitably involves greater consumption in W (I tried with the socket with current meter). It would be impossible, with the same bulb, to have a lower consumption with a higher brightness :-)
See you soon

**Comment by ultratoto14** [comment]
It would too difficult to manage the different bulbs but as mentioned, you can do it in HA.
If you have a a socket with power consumption, you can measure with 

- the minimum brightness in white mode
- the maximum brightness in white mode
- the minimum brightness in color mode
- the maximum brightness in color mode

Even you can change the color_temp as the bulb are using two different leds.
Then try to find the logic behind.

**Comment by SmartM-ui** [comment]
> It would too difficult to manage the different bulbs but as mentioned, you can do it in HA.
> If you have a a socket with power consumption, you can measure with
> 
>     * the minimum brightness in white mode
> 
>     * the maximum brightness in white mode
> 
>     * the minimum brightness in color mode
> 
>     * the maximum brightness in color mode
> 
> 
> Even you can change the color_temp as the bulb are using two different leds.
> Then try to find the logic behind.

Hi @ultratoto14 
I am already "working" in this sense, creating the sensor in HA where it takes as a reference either the brightness + RGBcolor and brightness + Color_Temp as the maximum brightness of white develops 7.5W while the maximum brightness of colors develops 2.5W. 
I just have to find a way to relate them on a 255 point scale

**Comment by postlund** [comment]
I will close this as the general use case is out of scope of this integration.
