### ISSUE TITLE
Protocol Version 3.4 Update Interval

### ISSUE THREAD

**Issue by milandzuris** [rospogrigio/localtuya#1425]
Protocol 3.4 have one Problem Update interval is every 30-60 seconds, im set to 10 seocnds and nothing change, on protocol 1 2 3 everything working correct.

**Comment by CodingGhost** [comment]
I have the same problem. scan interval seems to have no effect on 3.4

**Comment by rospogrigio** [comment]
#1251 merged, will be released soon. Closing issue.

**Comment by davidstrobl** [comment]
Hi, thx for your work. Is it possible to make new release to fix this issue?
