### ISSUE TITLE
RGB CCT can`t change more than two values from HA

### ISSUE THREAD

**Issue by Koliadjun** [rospogrigio/localtuya#145]
HA: 117.5
Local tuya: master (08/11/2020)
Can`t change two parametrs in the same time.

![2020-11-08 (1)](https://user-images.githubusercontent.com/14816869/98464088-0f135380-21c9-11eb-8043-62230250d8d2.png)

Change only color but not brightness. Also didn't work with scene in HA. Change only Color or color tempreture but not brightness.
Also didn't work "transition" when call servise 
light.turn_on 
{
entity_id: light.kids_room_test
transition: 60
rgb_color:
  - 255
  - 100
  - 100
brightness_pct: 47
}

**Comment by ultratoto14** [comment]
Yes, bug found here, will try to fix it soon.

**Comment by ultratoto14** [comment]
@Koliadjun you may give PR #146 a try, it may fix your problem.

**Comment by Koliadjun** [comment]
Can comfirm that two value are change in the same time. Scene HA work. Scene TUYA also work. But transition doesnt work.
Also dont change color in lovelace. In this picture form red to white (color piker)
![2020-11-10 (1)](https://user-images.githubusercontent.com/14816869/98724965-2b67e980-239d-11eb-811c-479eaf6bf810.png)
![2020-11-10](https://user-images.githubusercontent.com/14816869/98724970-2dca4380-239d-11eb-9656-b20a02c05222.png)

**Comment by ultratoto14** [comment]
The color picker status is expected, the color/white status is reflected in the bulb near the on / off button.
Transition is not yet supported.

**Comment by ultratoto14** [comment]
@Koliadjun the pr is merged, you can check if master is working for you. If it's ok, you can close that issue.

**Comment by ultratoto14** [comment]
Fixed with PR #146
