### ISSUE TITLE
Tuya stopped providing the localKey for personal use

### ISSUE THREAD

**Issue by TolianIPB** [rospogrigio/localtuya#1456]
Tuya stopped providing the localKey for personal use
https://support.tuya.com/en/help/_detail/K9tndtl21hlin

Now it's imposible to get localKey from
https://eu.iot.tuya.com
The whole API menu has been changed.

Any ideas how to get the API localKey now?

I have a network with several VLANs and Home Assistant on Raspberry PI4. I have to add Local Tuya devices manually.

**Comment by 0justin8** [comment]
I was just able to get my localkey from https://us.iot.tuya.com as per these instructions as before. [https://github.com/make-all/tuya-local#finding-your-device-id-and-local-key](url) I don't know if they changed the EU site or not, so maybe it is different there but it worked for me 2 days ago.

**Comment by chrjsorg** [comment]
This is super weird. I had the same problem, but my data (localKey, id, ip, ...) didn't change at all. I just reconfigured it, restarted HASS and it worked again. As far as I can see, none of the provided data has changed...

**Comment by ironboy1** [comment]
I think it is just related to door locks, cameras and other security related products. I was able to request my local key of my ceiling light jsut 10min ago from https://eu.iot.tuya.com/

**Comment by TolianIPB** [comment]
> 

Thanks a lot. Understood. My project required reactivation. Now everything is OK.

**Comment by TolianIPB** [comment]
My project required reactivation. Now everything is OK.
