### ISSUE TITLE
MQTT entities starts with device name not compatible with HA 2024.2.0

### ISSUE THREAD

**Issue by seederp2p** [rospogrigio/localtuya#1471]
So I think that you already saw this message at HA:

`Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.`

So here I am asking if this is going to be fixed in future versions.

Thank you so much!

**Comment by fumantsu** [comment]
localtuya as far as I remember doesn't use MQTT.

**Comment by seederp2p** [comment]
> localtuya as far as I remember doesn't use MQTT.

Hi!

You're correct.

I misread this due to some of the devices having similar name than the ones I've on localtuya.
