### ISSUE TITLE
Devices will be not listed

### ISSUE THREAD

**Issue by wesseli01** [rospogrigio/localtuya#1488]
## The problem
Devices are not visible

<img width="540" alt="image" src="https://github.com/rospogrigio/localtuya/assets/112374394/4585501f-1222-49c2-8248-334ab34dfe7b">

## Environment
- Localtuya version: v.5.2.1
- Home Assistant Core version: 2023.8.4
- [X] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ?
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [X] Are you using the Tuya/SmartLife App in parallel ?

## Steps to reproduce
1. Devices were installed in Smart App
2. Devices are visible in Developer Portal and are working

<img width="589" alt="image" src="https://github.com/rospogrigio/localtuya/assets/112374394/3388c57c-9078-4a83-b05a-e82ff935cd06"> 

4. I installed the local tuya version over HACS und put all data (ID, keys etc.) in the fields
5. I pushed the button configuration + add new devices 
6. Devices are not visible
7. The IoT service is running
8. The local firewall is not running, UDP Ports 6666 6667 are open in the local network
9. I downloaded the diagnose data - got following correct data 

```
"integration_manifest": {
    "domain": "localtuya",
    "name": "LocalTuya integration",
    "codeowners": [
      "@rospogrigio",
      "@postlund"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/rospogrigio/localtuya/",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/rospogrigio/localtuya/issues",
    "requirements": [],
    "version": "5.2.1",
    "is_built_in": false
  },
  "data": {
    "region": "eu",
    "username": "localtuya",
    "no_cloud": false,
    "client_id": "ayf...k77",
    "client_secret": "316...a97",
    "user_id": "eu1...Evk",
    "devices": {},
    "cloud_devices": {
      "bf896e7f2a51b470e3wtme": {
        "active_time": 1693933773,
        "biz_type": 18,
        "category": "wfcon",
        "create_time": 1693933773,
        "icon": "smart/icon/ay1559701439060fw6BY/b5f28ff251f0f3af885af39c4ef41e39.png",
        "id": "bf896e7f2a51b470e3wtme",
        "ip": "91.64.228.33",
        "lat": "52.5800",
        "local_key": "&Jk...i!W",
        "lon": "13.5600",
        "model": "341809",
        "name": "ZigBee Gateway SC",
        "online": true,
        "owner_id": "161800126",
        "product_id": "b25mh8sxawsgndck",
        "product_name": "ZigBee Gateway",
        "status": [],
        "sub": false,
        "time_zone": "+02:00",
        "uid": "eu16901804527441CEvk",
        "update_time": 1694051543,
        "uuid": "d489096a7d6720c3"
      },
      "bf8f656099a0158bb7kofw": {
        "active_time": 1693933937,
        "biz_type": 18,
        "category": "cz",
        "create_time": 1693933937,
        "icon": "smart/icon/ay1559701439060fw6BY/e76c813e99bc4dc66889e273747f7bb4.png",
        "id": "bf8f656099a0158bb7kofw",
        "ip": "",
        "lat": "52.5800",
        "local_key": "&Jk...i!W",
        "lon": "13.5600",
        "model": "One-way smart socket (EU)",
        "name": "Stecker 3",
        "node_id": "5c0272fffe28956f",
        "online": true,
        "owner_id": "161800126",
        "product_id": "kdi2o9m6",
        "product_name": "Socket",
        "status": [
          {
            "code": "switch_1",
            "value": false
          },
          {
            "code": "countdown_1",
            "value": 0
          },
          {
            "code": "relay_status",
            "value": "last"
          },
          {
            "code": "light_mode",
            "value": "relay"
          }
        ],
        "sub": true,
        "time_zone": "+02:00",
        "uid": "eu16901804527441CEvk",
        "update_time": 1694051543,
        "uuid": "5c0272fffe28956f"
      },
      "bfbf5957eb11a6be5c0djo": {
        "active_time": 1693934073,
        "biz_type": 18,
        "category": "cz",
        "create_time": 1693934073,
        "icon": "smart/icon/ay1559701439060fw6BY/5109c8744b03e0166fb4eb9536b862a2.png",
        "id": "bfbf5957eb11a6be5c0djo",
        "ip": "",
        "lat": "52.5800",
        "local_key": "&Jk...i!W",
        "lon": "13.5600",
        "model": "Keetat-P2103-EU",
        "name": "Stecker 2",
        "node_id": "a4c13883295244e5",
        "online": true,
        "owner_id": "161800126",
        "product_id": "j1v25l17",
        "product_name": "Socket",
        "status": [
          {
            "code": "switch_1",
            "value": false
          },
          {
            "code": "countdown_1",
            "value": 0
          },
          {
            "code": "add_ele",
            "value": 780
          },
          {
            "code": "cur_current",
            "value": 0
          },
          {
            "code": "cur_power",
            "value": 0
          },
          {
            "code": "cur_voltage",
            "value": 2330
          },
          {
            "code": "relay_status",
            "value": "power_off"
          },
          {
            "code": "light_mode",
            "value": "relay"
          }
        ],
        "sub": true,
        "time_zone": "+02:00",
        "uid": "eu16901804527441CEvk",
        "update_time": 1694051543,
        "uuid": "a4c13883295244e5"
      }
    }

```

## Provide Home Assistant traceback/logs
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1163, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 11: invalid start byte
2023-09-07 09:11:03.374 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
```

**Comment by wesseli01** [comment]
Thank you for the info but it is the same with xZetsubou fork.

**Comment by xZetsubou** [comment]
If you used my fork, try adding these devices manually and set the protocol version to `3.5`,  even the gateway not showing up?

**Comment by wesseli01** [comment]
The device was installed manually. The devices were not visible.

wesseli
Email: ***@***.***

**Comment by joel-cass** [comment]
I have the exact same problem. It would ve easy enough to set up the devices manually if the device key was not obfuscated in the diagnostics.

```
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.5.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.11",
    "docker": true,
    "arch": "i686",
    "timezone": "Australia/Sydney",
    "os_name": "Linux",
    "os_version": "5.10.0-8-686-pae",
    "run_as_root": true
  },
  "custom_components": {
    "meross_lan": {
      "version": "4.3.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "meross_cloud": {
      "version": "1.2.8",
      "requirements": [
        "meross_iot==0.4.5.7"
      ]
    },
    "xiaomi_gateway3": {
      "version": "3.3.2",
      "requirements": [
        "zigpy>=0.44.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "localtuya",
    "name": "LocalTuya integration",
    "codeowners": [
      "@rospogrigio",
      "@postlund"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/rospogrigio/localtuya/",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/rospogrigio/localtuya/issues",
    "requirements": [],
    "version": "5.2.1",
    "is_built_in": false
  },
  "data": {
    "region": "eu",
    "client_id": "wst...uk8",
    "client_secret": "9f8...edb",
    "user_id": "eu1...k94",
    "username": "localtuya",
    "no_cloud": false,
    "devices": {},
    "updated_at": "1694519391690",
    "cloud_devices": {
      "bfc0f7104bc6452136owkk": {
        "active_time": 1694504673,
        "biz_type": 0,
        "category": "wg2",
        "create_time": 1635993024,
        "icon": "smart/icon/ay1556838860681oKmdO/e47c08d07b3801b3ea8890b3f548bc7f.png",
        "id": "bfc0f7104bc6452136owkk",
        "ip": "210.50.136.160",
        "lat": "-33.8000",
        "local_key": "y6G...dW|",
        "lon": "151.0600",
        "model": "EMateGateWay",
        "name": "Wi-Fi Hub",
        "online": true,
        "owner_id": "81954003",
        "product_id": "lzjw7vgzngzrzy74",
        "product_name": "Wi-Fi Hub",
        "status": [],
        "sub": false,
        "time_zone": "+10:00",
        "uid": "eu16766742339227Vk94",
        "update_time": 1694514828,
        "uuid": "8258e4310e21d1c8"
      },
      "bff4f456877a9279c6rrew": {
        "active_time": 1694504841,
        "biz_type": 0,
        "category": "kg",
        "create_time": 1684989103,
        "icon": "smart/icon/ay1556838860681oKmdO/ab17f6e4e677bba7d3868a7a57cfe5b7.png",
        "id": "bff4f456877a9279c6rrew",
        "ip": "",
        "lat": "-33.8042",
        "local_key": "y6G...dW|",
        "lon": "151.0554",
        "model": "EMateWTT",
        "name": "Garden Watering",
        "node_id": "0E3",
        "online": true,
        "owner_id": "81954003",
        "product_id": "zrsgzc8jktsricjj",
        "product_name": "WX1 Tap Timer",
        "status": [],
        "sub": true,
        "time_zone": "+10:00",
        "uid": "eu16766742339227Vk94",
        "update_time": 1694506852,
        "uuid": "bff4f456877a9279c6rrew"
      },
      "bf66bf2da12b7129595a1s": {
        "active_time": 1694504817,
        "biz_type": 0,
        "category": "kg",
        "create_time": 1635993272,
        "icon": "smart/icon/ay1556838860681oKmdO/ab17f6e4e677bba7d3868a7a57cfe5b7.png",
        "id": "bf66bf2da12b7129595a1s",
        "ip": "",
        "lat": "-33.8042",
        "local_key": "y6G...dW|",
        "lon": "151.0554",
        "model": "EMateWTT",
        "name": "Evap Cooler Top-up",
        "node_id": "0E2",
        "online": true,
        "owner_id": "81954003",
        "product_id": "zrsgzc8jktsricjj",
        "product_name": "WX1 Tap Timer",
        "status": [],
        "sub": true,
        "time_zone": "+10:00",
        "uid": "eu16766742339227Vk94",
        "update_time": 1694506828,
        "uuid": "bf66bf2da12b7129595a1s"
      },
      "bfcf3af7050680362cs5gl": {
        "active_time": 1694504783,
        "biz_type": 0,
        "category": "kg",
        "create_time": 1635993250,
        "icon": "smart/icon/ay1556838860681oKmdO/ab17f6e4e677bba7d3868a7a57cfe5b7.png",
        "id": "bfcf3af7050680362cs5gl",
        "ip": "",
        "lat": "-33.8042",
        "local_key": "y6G...dW|",
        "lon": "151.0554",
        "model": "EMateWTT",
        "name": "Greenhouse Watering",
        "node_id": "0E1",
        "online": true,
        "owner_id": "81954003",
        "product_id": "zrsgzc8jktsricjj",
        "product_name": "WX1 Tap Timer",
        "status": [],
        "sub": true,
        "time_zone": "+10:00",
        "uid": "eu16766742339227Vk94",
        "update_time": 1694504783,
        "uuid": "bfcf3af7050680362cs5gl"
      }
    }
  }
}
```

**Comment by SubZero77** [comment]
I have the same problem - localtuya does not see any device. localtuya v5.2.1 and Home Assistant Supervisor 2023.09.2
All three values from  Tuya IoT Development Platform have been entered. There are no firewalls.
And the downloaded diagnostic data has all my Tuya devices.
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2023.9.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Moscow",
    "os_name": "Linux",
    "os_version": "5.10.110-rockchip-rk3588",
    "supervisor": "2023.09.2",
    "host_os": "Debian GNU/Linux 12 (bookworm)",
    "docker_version": "24.0.6",
    "chassis": "",
    "run_as_root": true
  },
  "custom_components": {
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "localtuya",
    "name": "LocalTuya integration",
    "codeowners": [
      "@rospogrigio",
      "@postlund"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/rospogrigio/localtuya/",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/rospogrigio/localtuya/issues",
    "requirements": [],
    "version": "5.2.1",
    "is_built_in": false
  },
  "data": {
    "region": "eu",
    "username": "localtuya",
    "no_cloud": false,
    "client_id": "7nv...7wh",
    "client_secret": "7f9...7d4",
    "user_id": "eu1...vcZ",
    "devices": {},
    "updated_at": "1694631425075",
    "cloud_devices": {
      "08700244a4e57c9c9cbb": {
        "active_time": 1694611735,
        "biz_type": 18,
        "category": "dj",
        "create_time": 1694611735,
        "icon": "smart/icon/001461404842469iWoLE/63c17cfc38dd723b0abf5d815eaa8dde.jpg",
        "id": "08700244a4e57c9c9cbb",
        "ip": "95.165.94.120",
        "lat": "55.9000",
        "local_key": "W:Q...)gZ",
        "lon": "37.6300",
        "model": "WF-DS01",
        "name": "\u0434\u0435\u0442\u0441\u043a\u0430\u044f",
        "online": true,
        "owner_id": "153443419",
        "product_id": "bSXSSFArVKtc4DyC",
        "product_name": "Dimmer switch",
        "status": [
          {
            "code": "switch_led",
            "value": false
          },
          {
            "code": "bright_value",
            "value": 14
          }
        ],
        "sub": false,
        "time_zone": "+03:00",
        "uid": "eu1681241075347OcvcZ",
        "update_time": 1694621141,
        "uuid": "08700244a4e57c9c9cbb"
      },
      "08700244a4e57c9cce4b": {
        "active_time": 1693660607,
        "biz_type": 18,
        "category": "dj",
        "create_time": 1681241485,
        "icon": "smart/icon/001461404842469iWoLE/63c17cfc38dd723b0abf5d815eaa8dde.jpg",
        "id": "08700244a4e57c9cce4b",
        "ip": "95.165.94.120",
        "lat": "55.9000",
        "local_key": "'-@...ukg",
        "lon": "37.6300",
        "model": "WF-DS01",
        "name": "\u043a\u0443\u0445\u043d\u044f",
        "online": true,
        "owner_id": "153443419",
        "product_id": "bSXSSFArVKtc4DyC",
        "product_name": "Dimmer switch",
        "status": [
          {
            "code": "switch_led",
            "value": false
          },
          {
            "code": "bright_value",
            "value": 14
          }
        ],
        "sub": false,
        "time_zone": "+03:00",
        "uid": "eu1681241075347OcvcZ",
        "update_time": 1694620654,
        "uuid": "08700244a4e57c9cce4b"
      },
      "08700248a6e59d9aee34": {
        "active_time": 1694611363,
        "biz_type": 18,
        "category": "dj",
        "create_time": 1693660780,
        "icon": "smart/icon/001461404842469iWoLE/63c17cfc38dd723b0abf5d815eaa8dde.jpg",
        "id": "08700248a6e59d9aee34",
        "ip": "95.165.94.120",
        "lat": "55.9000",
        "local_key": "y->...bMq",
        "lon": "37.6300",
        "model": "WF-DS01",
        "name": "\u0431\u043e\u043a\u043e\u0432\u043e\u0439 \u0432 \u0433\u043e\u0441\u0442\u0438\u043d\u043e\u0439",
        "online": true,
        "owner_id": "153443419",
        "product_id": "bSXSSFArVKtc4DyC",
        "product_name": "Dimmer switch",
        "status": [
          {
            "code": "switch_led",
            "value": false
          },
          {
            "code": "bright_value",
            "value": 14
          }
        ],
        "sub": false,
        "time_zone": "+03:00",
        "uid": "eu1681241075347OcvcZ",
        "update_time": 1694620368,
        "uuid": "08700248a6e59d9aee34"
      },
      "08500248a4e59c9abe34": {
        "active_time": 1693660845,
        "biz_type": 18,
        "category": "dj",
        "create_time": 1693660845,
        "icon": "smart/icon/001461404842469iWoLE/63c17cfc38dd723b0abf5d815eaa8dde.jpg",
        "id": "08500248a4e59c9abe34",
        "ip": "95.165.94.120",
        "lat": "55.9000",
        "local_key": ">c/...r/!",
        "lon": "37.6300",
        "model": "WF-DS01",
        "name": "\u043b\u044e\u0441\u0442\u0440\u0430 \u0432 \u0433\u043e\u0441\u0442\u0438\u043d\u043e\u0439",
        "online": true,
        "owner_id": "153443419",
        "product_id": "bSXSSFArVKtc4DyC",
        "product_name": "Dimmer switch",
        "status": [
          {
            "code": "switch_led",
            "value": false
          },
          {
            "code": "bright_value",
            "value": 14
          }
        ],
        "sub": false,
        "time_zone": "+03:00",
        "uid": "eu1681241075347OcvcZ",
        "update_time": 1694620368,
        "uuid": "08500248a4e59c9abe34"
      },
      "08700244a4e57c9abe5a": {
        "active_time": 1694611363,
        "biz_type": 18,
        "category": "dj",
        "create_time": 1693660426,
        "icon": "smart/icon/001461404842469iWoLE/63c17cfc38dd723b0abf5d815eaa8dde.jpg",
        "id": "08700248a4e57c9abe5a",
        "ip": "95.165.94.120",
        "lat": "55.9000",
        "local_key": "EZK....Dj",
        "lon": "37.6300",
        "model": "WF-DS01",
        "name": "\u043a\u043e\u0440\u0438\u0434\u043e\u0440",
        "online": true,
        "owner_id": "153443419",
        "product_id": "bSXSSFArVKtc4DyC",
        "product_name": "Dimmer switch",
        "status": [
          {
            "code": "switch_led",
            "value": true
          },
          {
            "code": "bright_value",
            "value": 78
          }
        ],
        "sub": false,
        "time_zone": "+03:00",
        "uid": "eu1681241075347OcvcZ",
        "update_time": 1694620367,
        "uuid": "08700244a4e57c9abe5a"
      }
    }
  }
}

**Comment by rospogrigio** [comment]
Sorry, I didn't notice the fork. I have introduced Zigbee support in PR #1493,  if anybody wants to test it and provide feedback, please comment in the PR.
