### ISSUE TITLE
Erro add Wifi Bulb RGB

### ISSUE THREAD

**Issue by ARafaelSF** [rospogrigio/localtuya#150]
I´m trying to add a RGB Bulb Wifi.
But getting error:  

- host: 192.168.68.102
    device_id: e?????????????????????a
    local_key: 5???????????5
    friendly_name: Abajur
    protocol_version: "3.1"
    entities:
      - platform: light
        friendly_name: Abajur
        id: 1
        color_mode: 21 # Optional, usually 2 or 21, default: "none"
        brightness: 22 # Optional, usually 3 or 22, default: "none"
        color_temp: 23 # Optional, usually 4 or 23, default: "none"
        color: 24 # Optional, usually 5 (RGB_HSV) or 24(HSV), default: "none"
        brightness_lower: 29 # Optional, usually 0 or 29, default: 29
        brightness_upper: 1000 # Optional, usually 255 or 1000, default: 1000
        color_temp_min_kelvin: 2700 # Optional, default: 2700
        color_temp_max_kelvin: 6500 # Optional, default: 6500

Erro:

Invalid config for [localtuya]: extra keys not allowed @ data['localtuya'][0]['entities'][0]['brightness']. Got 22
extra keys not allowed @ data['localtuya'][0]['entities'][0]['brightness_lower']. Got 29
extra keys not allowed @ data['localtuya'][0]['entities'][0]['brightness_upper']. Got 1000
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color']. Got 24
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_mode']. Got 21
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_temp']. Got 23
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_temp_max_kelvin']. Got 6500
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_temp_min_kelvin']. Got 2700
value is not allowed for dictionary value @ data['localtuya'][0]['entities'][0]['platform']. Got 'light'. (See /config/configuration.yaml, line 48

Any help

**Comment by postlund** [comment]
You must run from `master`, the release in HACS doesn't have those features yet.

**Comment by ARafaelSF** [comment]
> master

Could you help me how do this?

**Comment by postlund** [comment]
How did you install Home Assistant? You need to uninstall from HACS and copy all files in `custom_components/localtuya` (in this repo) into the same directory where your configuration.yaml is stored (I.e. `custom_components/localtuya`).

**Comment by ARafaelSF** [comment]
> How did you install Home Assistant? You need to uninstall from HACS and copy all files in `custom_components/localtuya` (in this repo) into the same directory where your configuration.yaml is stored (I.e. `custom_components/localtuya`).

Thank. The light is showing.

But is showing with state "Unavailable"

**Comment by postlund** [comment]
Anything useful in the log?

**Comment by ARafaelSF** [comment]
> Anything useful in the log?

the problem seems to be without id. I've tried several.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/common.py:294
Integration: LocalTuya (documentation, issues)
First occurred: 9:38:27 AM (3 occurrences)
Last logged: 9:38:28 AM

Entity light.abajur_1 is requesting unknown DPS index 1
Entity light.abajur_2  is requesting unknown DPS index 8
Entity light.abajur_3  is requesting unknown DPS index 9

**Comment by ultratoto14** [comment]
Hi @ARafaelSF, can remove your light from Home Assistant, ensure the phone app is really closed and do a DPs dump as described [here](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump) ?

**Comment by ARafaelSF** [comment]
> Hi @ARafaelSF, can remove your light from Home Assistant, ensure the phone app is really closed and do a DPs dump as described [here](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump) ?

I don´t now why, but i tried all ids again e star work, with id 20

- host: 192.168.x.x
  device_id: e?????????????????????e
  local_key: 2????????????a
  friendly_name: Light Main
  protocol_version: "3.3"
  entities:
    - platform: light
      friendly_name: Light
      id: 20
      color_mode: 21
      brightness: 22
      color_temp: 23
      color: 24
      brightness_lower: 29
      brightness_upper: 1000
      color_temp_min_kelvin: 2700
      color_temp_max_kelvin: 6500


Thanks
