### ISSUE TITLE
Error when controlling RGB bulbs

### ISSUE THREAD

**Issue by albertooka** [rospogrigio/localtuya#151]
Hello!
I've been trying to add my RGB smart bulbs controlled by the Smart Life app to my Home-Assistant server through LocalTuya. I have added the bulbs through the Home-Assistant web interface, the problem I have is that when I add the RGB bulbs, the RGB color option does not appear in the configuration options. I can control the bulbs perfectly from Home-Assistant, I can control the brightness and white color temperature, but I do not appear the option of RGB colors. Searching in the Home-Assistant community, I found that adding the following options to the configuration file, you can get the RGB option to appear. I get the color option to appear, but when I try to set a color, I get an error (Error when calling the light/turn_on service). I even get an error if I try to set a color from the developer tools section of Home-Assistant.
I hope that with your help I will be able to change the colors of my lights.

This is the configuration I found in the Home-Assistant community:
`homeassistant:
 customize:
    light.kitchen:
      supported_features: 63`

Screenshot of the section to add LocalTuya integration:
![IMG_20201111_113405](https://user-images.githubusercontent.com/51706247/98801442-15e0d700-2412-11eb-83a6-6901978404a2.jpg)

**Comment by postlund** [comment]
Color support has not been released yet in HACS, so you will have to install from `master` to get it working.

**Comment by albertooka** [comment]
Ok. I will install the master version and test it. Thank you!

**Comment by albertooka** [comment]
It's already solved! Thank you very much!
