### ISSUE TITLE
power plug turn off and back on for no reason

### ISSUE THREAD

**Issue by rdeangel** [rospogrigio/localtuya#152]
I noticed that when monitoring a power plug with flactuating energy reading which constantly change the power plug occasionally turns off and immediately powers back on. 
This stops when I remove it from localtuya.

I also have to use both localtuya and the regular tuya integration in order to power on and off the plug. I don't seem to be able to change the on and off status with localtuya alone.

**Comment by rdeangel** [comment]
ok the issue I described above was actually user error. One of my automation was unnecessarily turning the plug off when it was already off causing the state of the sensor to flicker. I fixed that by putting a condition before the action.

What is annoying though is the transitioning between states has always the intermediate state "unavailable" which causes issue with automations when the defined conditions include "on" to "off" transitions and viceversa.

**Comment by postlund** [comment]
You should not see any `unavailable` state changes unless there's any issue of some sort. Do you have any errors in the log?

**Comment by rdeangel** [comment]
Hi Thanks for looking into this.

the below is what I'm referring to visually in home assistant:
![localtuya](https://user-images.githubusercontent.com/6622982/99200616-49b75600-279e-11eb-9de2-9200c9ae67c7.gif)

and this is what I can see in the logs:
![image](https://user-images.githubusercontent.com/6622982/99200703-c813f800-279e-11eb-895f-fc92a5f49f97.png)

**Comment by postlund** [comment]
@rdeangel That looks really strange, but at least there are a few errors. Can you post the error log?

**Comment by rdeangel** [comment]
see logs here: [localtuya_logs.txt](https://github.com/rospogrigio/localtuya/files/5548585/localtuya_logs.txt)

**Comment by postlund** [comment]
Are you using the tuya integration as well? You have to disable that. Looks like one of the devices always fail to decide the incoming payload. Did you configure via YAML or config flow? If YAML, how does the config look like?

**Comment by rdeangel** [comment]
Initially I deleted the tuya integration and tried to get everything to work with localtuya but I was not succesfull.

I use the tuya integration along with localtuya because I couldn't get localtuya to change the status of the plug (on and off), I can only successfully read the energy readings with localtuya (except for the issue mentioned).

Also because Tuya is unable to read the plug status in realtime when switched via the plug button I use the localtuya state changes (on and off) to update the tuya integration switch object. 
I know it's messy and probably the rootcause of the issue but it's the only way I could get it to fully work (except for the errors/unavailable intermittent issue)

I assumed localtuya was unable to change the state of my plug (I thought it was odd, but I'm guessing based on what you said that it should work fine)

I configured it manually with yaml and tried both style of config, switch and sensor based, both had issues.

[local_tuya.txt](https://github.com/rospogrigio/localtuya/files/5549416/local_tuya.txt)

**Comment by postlund** [comment]
Ok, so I'm not really sure where we are right now. Based on the log earlier, I got the feeling that you had multiple power plugs, was that the case? It would be great if you could test according to this:

1. Remove both the tuya and localtuya integrations so you are on a clean slate
2. Add *one* power plug to localtuya
3. Use the config from your previous post, but use the switch instead of binary_sensor
4. Verify if you can turn on/off the plug from Home Assistant
5. Verify if state is reflected in Home Assistant when you press the physical button on the plug
6. Keep monitoring the debug log (attach it here if it doesn't work as expected)

**Comment by rdeangel** [comment]
I'm afraid it just won't work, I'm using "switch" instead of "binary_sensor" and while I can monitor I can't interact with the plug without tuya.

See file attached (I tried to switch from off to on twice from the switch.localtuya object but the switch just goes back to off after a couple of seconds and I get the error "Failed to set DP 1 to 1" at the same time)
[local_tuya_logs_no_state_change.txt](https://github.com/rospogrigio/localtuya/files/5550442/local_tuya_logs_no_state_change.txt)
In the logs you'll also see messages related to me switching the plug from off to on (again twice), when I do this the switch on home assistant passively detects on and off appropriately.

**Comment by postlund** [comment]
I get the feeling that something isn't quite working with the encryption. Would it be possible for me to get access to the plug somehow so I can try some things out? It would be a lot easier than trying to pass commits bank and forth.

**Comment by rdeangel** [comment]
"Would it be possible for me to get access to the plug somehow" how do you suggest?

these are the plugs btw:
https://www.amazon.co.uk/Slitinto-Monitoring-Control-Function-Required/dp/B07DVXNNH4/ref=sxts_sxwds-bia-wc-nc-drs1_0?cv_ct_cx=slitinto&dchild=1&keywords=slitinto&pd_rd_i=B07DVXNNH4&pd_rd_r=03053e4c-4832-4f46-b6ae-ff22d83fa667&pd_rd_w=GlbkP&pd_rd_wg=vmUCU&pf_rd_p=344521d5-1bc6-4c7a-9776-9c81f49df30a&pf_rd_r=71WYJHT4AJHBGQAVFW1S&psc=1&qid=1605626641&sr=1-1-0f636240-5ebc-47e0-a5f7-bb2a7fa20976

**Comment by postlund** [comment]
Preferably if we could set up a tunnel of some sort or if you could hook it up to a virtual machine I can access. I would need some way to run python code and connect to it.

**Comment by rdeangel** [comment]
Sure I can create an ubuntu vm and a wifi on an isolated vlan and give you access to do your tests via zerotier.

Does that work?

**Comment by postlund** [comment]
Sounds perfect 👌

**Comment by rdeangel** [comment]
All working now.

This was not a bug rather just the plain and old user error, for not having set the correct key.

Watch out by the way when you reassociated the plug or device with the smart app your local_key changes so you need to go and get it again.

Thanks @postlund for your help, I hate to waste someone's time, but that's just what I did in this occasion.
