### ISSUE TITLE
LED Strip not changing to 'colour' mode if it's in 'scene' mode

### ISSUE THREAD

**Issue by SerAlbi** [rospogrigio/localtuya#157]
On some lights, like two of my LED strips, changing the color of the LEDs while a 'scene' mode is active, does nothing because the mode value is not automatically switched from 'scene' to 'colour'.
The issue is present because in line 216 of light.py the if doesn't account for a 'scene' mode but only for the white mode.

```
 states[self._config.get(CONF_COLOR)] = color
 if self._is_white_mode:
      states[self._config.get(CONF_COLOR_MODE)] = "colour"
```
Removing the if (so that the light always switches to 'colour' mode if a color is selected seems to solve the issue temporarily.

I don't actually have a dev environment to fix/test the issue myself so i don't know if this could cause any other problems at the moment.

**Comment by ultratoto14** [comment]
Hi, can you check with #146 ?

**Comment by SerAlbi** [comment]
Hi @ultratoto14 what do i need to do specifically? Sorry i'm not very active on github. I checked #146 and that particular 'if' is still present but there are a lot of code changes, merging them with my current installation doesn't seem to solve the issue atm but probably i did something wrong.

**Comment by ultratoto14** [comment]
Hi @SerAlbi , If you look at the code you specified [line 216](https://github.com/rospogrigio/localtuya/pull/146/files#diff-b43f756f845ad2b099fd44246f0c1b99ad2e6eb9345056609f18b666ed8d77b9L216), the PR seems to fix it. 

You can easily test it by doing:
- Go in the conversation of the PR #146 
- Just below the title, you will see : 'someone' wants to merge X commits into rospogrigio:master from <a branch>. Click on the branch
- You will then be redirected to the branch that wants to be merged. On the left upper side, click on the green 'Code' button.
- Select download zip
- This zip will contain the complete code of the pull request, you just need to replace your custom_component/localtuya directory in you home assistant install by the one in the zip.

This PR introduces the support of the scenes in this integration. If you are able to test it, do not hesitate to let a comment in the PR conversation.

**Comment by SerAlbi** [comment]
Ok thanks! Done some testing and got mixed results. My RGB bulbs works fine but my LED strips not. I'll post an update on the PR #146 for further info.

**Comment by ultratoto14** [comment]
Should be fixed in master, @SerAlbi if you want to do a final check.

**Comment by SerAlbi** [comment]
@ultratoto14 done some testing with the master branch. There seems to be an issue in which the 'Music' scene is always shown even if 'music_mode' is set to False in the .yaml configuration.

All the other features seems to work correctly.

**Comment by ultratoto14** [comment]
@SerAlbi  It's linked to the list of scenes you sent me 😄, is it only on your RGB light or on all ones ?

P.S. I initiated a [wiki page](https://github.com/rospogrigio/localtuya/wiki/Known-working-and-non-working-devices) for known devices if you paste the data of yours here i can add them to the list.

**Comment by postlund** [comment]
@ultratoto14 Great initiative! I suggest that we try to move it into one or more config files that we check in, so we can use it programmatically with the integration later. We could write a small script that generates HTML output and serve it via GitHub pages. We should also map it to product key, so we now exact product. I will try to come up with a PR that saves the product key and allows for easy extraction from the UI.

**Comment by SerAlbi** [comment]
> edit: Found it, not link to your scene list. Will push a fix soon.
Tested. It's working ok now :)

>P.S. I initiated a wiki page for known devices if you paste the data of yours here i can add them to the list.

My LED strip is a:
- Smart LED Strip
- Brand: Etersky
- FW: 1.4.0
- Type: RGB
- ID: 20
- Color mode: 21
- Color: 24
- Scene: 25

Other data i'm not really sure, for example i have a DP 26 but it's always 0...

Then i have:

- RGBW Smart Bulb
- Brand: Tekin
- FW: 1.6.1
- ID: 1
- Color mode: 2
- Brightness: 3
- Color temp: 4
- Color: 5
- Brightness lower: 25
- Brightness upper: 255
- min kelvin: 2800
- max kelvin: 6200
- scene: 6

**Comment by ultratoto14** [comment]
@SerAlbi The bug should be fixed in master, please update and check. Thanks for data, wiki updated.

@postlund Agree with you. We should keep it like this until we have all the necessary data to store in a file. Ensuring that configuration entries are stable.

**Comment by SerAlbi** [comment]
@ultratoto14 yes already tested and it's working great :)

**Comment by ultratoto14** [comment]
So i can close the issue. Thanks
