### ISSUE TITLE
Fan appears as unavailable

### ISSUE THREAD

**Issue by joe-sydney** [rospogrigio/localtuya#165]
When I tried to add my Tuya-based Fan (using the example given, id=3), the fan.living_room_fan entity came up as unavailable. When I added it as a switch (switch.living_room_fan), it worked fine, although as expected I can only turn the fan on and off.

On Tuya IOT Platform, the details of the fan are:
Product ID: 7lvkraqxxdee6dkc Type: Fan

Code | Type | Values
switch | Boolean | {true,false}
mode | Enum | {"range":["nature","sleep","fresh","smart","strong","closed"]}
fan_speed | Enum | {"range":["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26"]}
switch_horizontal | Boolean | {true,false}
countdown | Enum | {"range":["0","1","2","3","4","5","6"]}

Does the script for fan (fan.py) need to be modified? In practical terms, I only need to be able to turn it on and off and change the speed. Being able to control oscillation and mode is optional.

Cheers
Joe

**Comment by postlund** [comment]
It should not have to be modified for basic functionality, we don't support all those speeds yet however. I would advise you to test running with the latest commit from `master` as improvements have been made that is not in the latest releases version.

**Comment by joe-sydney** [comment]
I tried both the release and the master branches and neither seems to work. I also tried both the Yaml and the "config flow" method and neither works. The basic config for the switch version is shown below, and when I changed that to fan, it become "unavailable". (I tried 1 and 3 for the id and that had no impact.)
localtuya:
  - host: x.x.x.x
    device_id: !secret my_device_id
    local_key: !secret my_local_key
    friendly_name: Living Room Fan
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Living Room Fan
        id: 1

**Comment by postlund** [comment]
Then it would be great if you enabled debug logs and attached them here so I can troubleshoot further.

**Comment by joe-sydney** [comment]
I saw there were exceptions per below. It was possible to set speed values but issue seemed to be getting status (hence showing unavailable).

I made some changes to use self.dps("1") rather than self._status["dps"]["1"] and similarly for setting the speed value and this seems to work now, eg:
        #self._is_on = self._status["dps"]["1"]
        self._is_on = self.dps("1");

In the process, I changed the speed values to work for the fan which accepts levels 1 to 8. :)

Applying the same idea to Oscillation has improved it so the entity doesn't go unavailable, but the Oscillation toggle on Home Assistant doesn't do anything. So for now, i've just removed the Oscillation capability completely.

XXX: 2020-11-18 12:39:28 ERROR (SyncWorker_6) [homeassistant.util.logging] Exception in _update_handler when dispatching 'localtuya_45040540500291bb77f3': ({'1': False, '2': 'normal', '3': '5', '4': 'off', '6': '0'},)
XXX: Traceback (most recent call last):
XXX:   File "/home/homeassistant/.homeassistant/custom_components/localtuya/common.py", line 239, in _update_handler
XXX:     self.status_updated()
XXX:   File "/home/homeassistant/.homeassistant/custom_components/localtuya/fan.py", line 139, in status_updated
XXX:     self._is_on = self.dps(self._dps_id)
Nov 18 12:39:28 meow hass[15958]: AttributeError: 'LocaltuyaFan' object has no attribute '_dps_id'

**Comment by postlund** [comment]
There'a a typo in the code, so nothing will really work... But I submitted a fix for it in #178. Would be great if you tried that.

**Comment by joe-sydney** [comment]
I've updated to the latest release, and setting fan on/off plus speed control works (DP 3). Oscillation control (DP 4) throws exceptions as per below log. While setting up the fan on the HA integrations interface, the integration correctly gets the status of DP 4 but trying to set that DP fails, and makes the entity become momentarily unavailable.

Nov 29 17:54:54 XXXXXXXX: 2020-11-29 17:54:54 DEBUG (MainThread) [custom_components.localtuya.pytuya] [XXXXXXXX] Sending command set (device type: type_0a)
Nov 29 17:54:54 XXXXXXXX: 2020-11-29 17:54:54 DEBUG (MainThread) [custom_components.localtuya.pytuya] [XXXXXXXX] Send payload: b'{"devId":"xxxx","uid":"xxxx","t":"xxxx","dps":{"4":false}}'
Nov 29 17:54:54 XXXXXXXX: 2020-11-29 17:54:54 DEBUG (MainThread) [custom_components.localtuya.pytuya] [XXXXXXXX] Waiting for sequence number 2
Nov 29 17:54:59 XXXXXXXX: 2020-11-29 17:54:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [XXXXXXXX] Sending command heartbeat (device type: type_0a)
Nov 29 17:54:59 XXXXXXXX: 2020-11-29 17:54:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [XXXXXXXX] Send payload: b'{}'
Nov 29 17:54:59 XXXXXXXX: 2020-11-29 17:54:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [XXXXXXXX] Waiting for sequence number -100
Nov 29 17:54:59 XXXXXXXX: 2020-11-29 17:54:59 ERROR (MainThread) [custom_components.localtuya.common] [XXXXXXXX] Failed to set DP 4 to 0
Nov 29 17:54:59 XXXXXXXX: Traceback (most recent call last):
Nov 29 17:54:59 XXXXXXXX:   File "/home/homeassistant/.homeassistant/custom_components/localtuya/common.py", line 183, in set_dp
Nov 29 17:54:59 XXXXXXXX:     await self._interface.set_dp(state, dp_index)
Nov 29 17:54:59 XXXXXXXX:   File "/home/homeassistant/.homeassistant/custom_components/localtuya/pytuya/__init__.py", line 478, in set_dp
Nov 29 17:54:59 XXXXXXXX:     return await self.exchange(SET, {str(dp_index): value})
Nov 29 17:54:59 XXXXXXXX:   File "/home/homeassistant/.homeassistant/custom_components/localtuya/pytuya/__init__.py", line 440, in exchange
Nov 29 17:54:59 XXXXXXXX:     msg = await self.dispatcher.wait_for(seqno)
Nov 29 17:54:59 XXXXXXXX:   File "/home/homeassistant/.homeassistant/custom_components/localtuya/pytuya/__init__.py", line 239, in wait_for
Nov 29 17:54:59 XXXXXXXX:     await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
Nov 29 17:54:59 XXXXXXXX:   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
Nov 29 17:54:59 XXXXXXXX:     raise exceptions.TimeoutError()
Nov 29 17:54:59 XXXXXXXX: asyncio.exceptions.TimeoutError
