### ISSUE TITLE
Add new device not possible and error "subscription ... has expired" in IOT development plattform

### ISSUE THREAD

**Issue by jove01** [rospogrigio/localtuya#1678]
Hi 

I want to add a new device to local tuya integration. 

![image](https://github.com/make-all/tuya-local/assets/116289742/dab0394e-4035-4622-b29f-159af318b061)

But there is no local key
![image](https://github.com/rospogrigio/localtuya/assets/116289742/12c98a8b-b47a-4751-9d59-0f4cc1e80abf)

so I looked into the IOT development plattform in my project to see the local key there. My device I found
![image](https://github.com/make-all/tuya-local/assets/116289742/f220fe2b-12ba-4dc7-9d34-585e158b501a)

But in the device detail there is an error

`{
  "code": 28841002,
  "msg": "No permissions. Your subscription to cloud development plan has expired.",
  "success": false,
  "t": 1708637869996,
  "tid": "a063cb30d1ca11eea1957edaaa357452"
}`

So I did not know, is the doorbell supported in local Tuya and is  issue there, or is the permission the reason to get no local key or have I done an error?

I didn't know the exact device information, because the doorbell is integrated in my letterbox.

I hope, you can help and say, what can I do.

**Comment by joederpoliveira** [comment]
Same error here. :(

I bought three lights, added them to the Smart Life App, but couldn't set them up in Home Assistant.

My subscription had also expired. This error happened after I renewed it

**Comment by joederpoliveira** [comment]
Same error here. :(

I bought three smart bulbs, added them to the Smart Life App, but couldn't set them up in Home Assistant.

My con

**Comment by jove01** [comment]
I found the solution here
https://community.home-assistant.io/t/other-options-when-tuya-iot-expired/542767/13

**Comment by Inglan** [comment]
Same issue in #1214
