### ISSUE TITLE
max_temp not correct for device

### ISSUE THREAD

**Issue by leejoow** [rospogrigio/localtuya#1760]
I've connected the Poolex Q-Line Full Inverter 7kW via this integration to Home Assistant. 
It reports the max_temp as 35 degree, which is not correct.  Via the display I can set the temperature up to 40 degrees.

This was never a problem, through the service call set_temperatur I could set it to the needed 37 degrees, but in the last Home Assistant update there is now a validation against the max_temp. This has the effect I now can only set the temperature to 35 degrees, which is not enough. Could this range be updated?

![image](https://github.com/user-attachments/assets/1cdb56b2-6163-47d6-b032-ce638418dfdc)

**Comment by marco73** [comment]
@leejoow, You can try to set a custom value for the max_temp in the config like:
homeassistant:
  customize:
    climate.warmtepomp_bad:
      max_temp: 40

**Comment by leejoow** [comment]
@marco73 I have just tried this and in the UI the slider now visually goes up to 40 degrees. However, I am not able to set it to anything higer then the initial max_temp

**Comment by marco73** [comment]
I have a similar issue, but than with Fahrenheit. I can set the value using the services. maybe you can too.

![image](https://github.com/user-attachments/assets/e6b9c187-b1d2-42e4-94ac-5172eefa844a)

I did see another post asking for a new release. I did see code changes in regards to the new HA update, but the current release in HACS is a year old. Hopefully a new release will be made, or I need to find out how to make a manual update from this repo in HA.

**Comment by leejoow** [comment]
> I have a similar issue, but than with Fahrenheit. I can set the value using the services. maybe you can too.
> 
> ![image](https://private-user-images.githubusercontent.com/397936/361480580-e6b9c187-b1d2-42e4-94ac-5172eefa844a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODkxNzEsIm5iZiI6MTcyNDY4ODg3MSwicGF0aCI6Ii8zOTc5MzYvMzYxNDgwNTgwLWU2YjljMTg3LWIxZDItNDJlNC05NGFjLTUxNzJlZWZhODQ0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxNjE0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmU4NzIyYjBlYzAyN2JhMDc0MDk4OWI0OGY5N2UxNzRlMjQ5NzBjNTA2Y2ExNTM2YjZmOTU4ZDIxZTNmOWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4_uhpQtfpssKJpJDb-NBbrNSG2h6S2aYbqAkDZQ9zOg)
> 
> I did see another post asking for a new release. I did see code changes in regards to the new HA update, but the current release in HACS is a year old. Hopefully a new release will be made, or I need to find out how to make a manual update from this repo in HA.

Unfortunately not, since version 2024.8.0 the set temperature action is checked againt the min and max temperatures. When setting this max temperature through config the action is still validated against the initial settings.

**Comment by leejoow** [comment]
After reconfiguring the integration I was able to change the max temperature

**Comment by gunnjr** [comment]
Piling on to an old thread in hopes getting some insight. I'm battling an issue closely related to this, whereby the max_temp that I have defined via `customize:`is sometimes (but not always) ignored, resulting in a temp out of range error. 

Below it the pattern I am observing. Have others on this thread observed similar??

- I have a climate device (Moen smart shower exposed to HA via HomeKit device) for which I have defined min and max temps as follows:
```yaml
customize:
  climate.master_shower:
    min_temp: 65
    max_temp: 120
```
- Occasionally (frequently but not always immediately after HA restart), Home Assistant will get into a state whereby it imposes the default min and max temps and yields a temp out of range error if I try **_FROM WITHIN A SCRIPT_** to set temp above 95 (the default max).
- When the system is in the above state, I can successfully set the temp above 95 from a climate card on a dashboard....**_AND..._**
- After setting the temp from the UI, the system changes to using my custom min and max temps and henceforth I can run the script and successfully set the temp above 95.
- Inevitably, at some point (usually 12+ hours), the system returns to using defaults and the script again fails when attempting to set temp above 95.
- If I go back to UI and set temp, the script works again, and so on, and so on.

**My questions to those on this thread:**
1. Were your out of range error encountered when setting temp from within a script/automation?
2. Were you able to sucessfully set temps from the UI?
3. If yes to 1 &2, did setting the temp from the UI temporarily resolve the range issue as it does for me?
