### ISSUE TITLE
Multipe Socket with USB - Only able to configure 1 socket

### ISSUE THREAD

**Issue by johnjoemorgan** [rospogrigio/localtuya#180]
I have a generic 4 outlet/4 USB Tuya extension plug/gang socket (My device is under the "Lasco" brand in the Philippines but it's a generic Tuya device sold worldwide)  With Local  Tuya manual integrated using milesperhour/fastcolors/stast1 I can confure the device with ID1-4 for the socket and ID7 for the 4 USBs.

With the HACS integration - clean install i.e. removed all Tuya integrations - I can only set up one ID/device.  Is this an issue with the (Cheap) device or a bug with the integration?

**Comment by postlund** [comment]
What have you tried? You should just keep adding entities, one switch per socket, until you have one for each socket you want to control.

**Comment by johnjoemorgan** [comment]
@postlund After the first ID is added if I try to add another it says this device is already configured.  I tried manually discovering as well but had the same result

**Comment by postlund** [comment]
@johnjoemorgan You should not add a new device but a new entity. After adding the first switch, pick `switch` again in the dropdown menu and untick `Do not add any more entities`. This will allow you to add another switch, just like the first one (but pick the next id). Continue until you have added you want.

**Comment by johnjoemorgan** [comment]
Many thanks for your patience with user error problems! 👍 All set up and working great with 2 switches with power sensors plus the 4 extension/USB working great.  Many thanks again.
