### ISSUE TITLE
Update broke my devicea

### ISSUE THREAD

**Issue by Maxxxel** [rospogrigio/localtuya#1827]
Just installed the latest update and now all my devices and entities are dead :3

My cloud API access has also expired. I thought it was only needed for one time configuration?

**Comment by binarydad** [comment]
I might be having a similar issue... I'm trying to add a device and it's not populating the local key and name. Reauthentication was successful. Not sure what changed.

**Comment by gptech2444** [comment]
same here

**Comment by checkiecheck** [comment]
@Maxxxel , had the same, but going through the 'configure' steps. Edit existing device and submit all values again, made it back to life for me again.
I think it needs to reconfiugre the deprecated constants to new constants . (could have been in migrations script, but this is also wroking and ok if there are not too many devices)

**Comment by Maxxxel** [comment]
My problem was that my API access was shutdown.. was using it for years for free now. I've decided to go with the official tuya plugin + tuya extended. Was exactly what I needed without any problems.
