### ISSUE TITLE
Sensor

### ISSUE THREAD

**Issue by ahmaddxb** [rospogrigio/localtuya#184]
I see we can obtain the below as sensors, can we get the total KWh and today KWh like in the tuya app also?

current: 18 # Optional
current_consumption: 19 # Optional
voltage: 20 # Optional

**Comment by postlund** [comment]
You will have to set up an `integration` sensor for that. The devices does not calculate total consumption themselves, it's normally handled by the cloud.

**Comment by postlund** [comment]
I will close this as it's out of scope for this integration.
