### ISSUE TITLE
Problem with covers

### ISSUE THREAD

**Issue by darth-aragoth** [rospogrigio/localtuya#186]
Hi,
after one of latest HA updates I noticed that all my covers are offline. I checked log and for every device I see error like:

`Exception in _update_handler when dispatching 'localtuya_xxxxxxxxxx': ({'1': '3'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 245, in _update_handler self.status_updated() File "/config/custom_components/localtuya/cover.py", line 185, in status_updated time_diff = time.time() - self._timer_start TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'`

**Comment by darth-aragoth** [comment]
I discovered something strange, when I launch any scene that changes position of a cover, it becomes online.

**Comment by rospogrigio** [comment]
Issue being fixed with PR #189 .
