### ISSUE TITLE
Suddenly (some) Tuya smart plugs not giving power information anymore

### ISSUE THREAD

**Issue by Thijs90** [rospogrigio/localtuya#1861]
## The problem
I've had some struggles with the Tuya local integration.

I've got 5 smart plugs from which 1 is connected to the washing machine. This one worked seem to work fine for a long time. Now I updated Home Assistant to the newest version and SOME (only some) suddenly not working. Before the update I also had 2 other smart plugs which did not give information about power, etc. anymore.

They all got the same configuration and are all of the same type. Also I see the right information in the Tuya Smart application on the phone for all devices. The smart plugs work normally and can see all information.

I've tried reloading and restarting home assistant several times. Also I've tried to edit the smart plug in the integration and saving it again. Does not do anything...

Weird thing is:
In the Tuya application there is the option to go to the smart plug and click 'Detect network capacity'. On the devices that don't show information in Home Assistant this option does not connect to the network. On the device that works I do get a response. Weird thing is that I do see all the information in the Tuya application (power, current, etc.) and can switch the power to.

Is there someone who can please help me?! All my automations do not work anymore sadly :(

## Environment
- Localtuya version: newest version (did not change when it break)
- Home Assistant Core version: 2024.12.0

## Additional information
![Config-tuya-local-all](https://github.com/user-attachments/assets/1fcd2357-3d97-4873-81f2-8348aa3e9201)
![Config-tuya-local](https://github.com/user-attachments/assets/5ee6b1a0-b52b-4dfd-85e7-9909d2d3733a)

**Comment by RemyWegman** [comment]
Had sort of the same problem, a power cycle from the plugs and a restart of homeassistant seemed to have worked for me.

**Comment by Thijs90** [comment]
Thanks! This helped! 

I disconnected all of the smart plugs. Installed them again. In the Tuya application I checked for connectivity to the network. Reloaded the Tuya Local intergration and now it works again.
