### ISSUE TITLE
Question about add more sensors to LocalTuya

### ISSUE THREAD

**Issue by lfuszara1** [rospogrigio/localtuya#188]
I configured LocalTuya by panel, how can I add more sensors to device?
Or how can I export configuration of configured devices to yaml file?

**Comment by postlund** [comment]
You currently can't, it's in my roadmap but I haven't finished support for that yet. I think I'm probably not that far off with support for adding additional entities, but I'm not done with it yet.

**Comment by postlund** [comment]
And right, I finished it yesterday. So you can try #191 if you like or wait until it's merged.
