### ISSUE TITLE
Removing a device from the cloud after obtaining keys

### ISSUE THREAD

**Issue by NathanVanCleave** [rospogrigio/localtuya#190]
I may be misunderstanding what this tool does so please correct my if I'm wrong. 

I would like to delete my devices from the Tuya app/cloud now that I have the keys and local control, but doing so appears to break the connection with LocalTuya as well. Does LocalTuya require devices still be connected to the cloud? Is there a way to set them up from a factory reset (once I have the keys) and completely remove the Tuya cloud control?

**Comment by NathanVanCleave** [comment]
I apologize. I did not read through the closed issues and found my exact question in there.

And by the way, thanks a million for all your (and others) hard work on this!!

**Comment by colethegamer123** [comment]
What was the solution here please? I cannot find the answer you mentioned. I added 3 light, Obtained keys and added with local tuya, after I delete them from the app, connection is broken. Thanks!

**Comment by NathanVanCleave** [comment]
From what I understand, you cannot remove the devices from the Tuya app. I can't find the closed issue that answered my original question, but I've seen this posted several times. You have to leave the devices in the app AND disable access to the internet at your router after you've got localtuya working if you want them out of the cloud. I had some issues with the latter and ended up not using localtuya. Instead, I upgraded my home network/router and put all my IoT devices on a VLAN with a firewall blocking unwanted traffic from my main network. So, still in the cloud but at least more secure for now. I have yet to test localtuya on my upgraded network, but I plan to.
