### ISSUE TITLE
Can't turn light off?

### ISSUE THREAD

**Issue by koffienl** [rospogrigio/localtuya#198]
I have a LSC Smart E14 RGB bulb from retailer Action in the Netherlands.
The light works, I can change the color in HA and the color will change on the bulb. However, when I turn the light off in HA, the bulb physically changes to some warm color. When I turn the light back on in HA, the light is set to color temperature mode, but I can switch back to the desired color with the color picker.

![Capture](https://user-images.githubusercontent.com/6832264/100543990-2fc44b80-3253-11eb-95c9-a53dab2a4af2.JPG)

**Comment by ultratoto14** [comment]
Try to set the brightness upper value to 255, it should match the max value of DP 3 and 4.

A wrong value may put the light in an unkown state.  Use the Tuya APP to switch the light to different settings, white/color/color temp and then switch it off for a while. 
Report if it fixes the issue.

**Comment by koffienl** [comment]
Changing the brightness upper value to 255 didn't changed anything. I don't have the light in Toya APP so have to test some more tomorrow.

**Comment by ultratoto14** [comment]
Hi @koffienl, I didn't look correctly yesterday as it seems that you set the DP id to 4 (first line of your picture) and it should be 1.
Try to remove the bulb and configure as follow:

![image](https://user-images.githubusercontent.com/3328573/100627070-d9c0d800-3326-11eb-89f6-a7028428d028.png)

**Comment by koffienl** [comment]
Yes, that did the trick. Thank you!
