### ISSUE TITLE
Update Compatibility

### ISSUE THREAD

**Issue by DavidFFerreira** [rospogrigio/localtuya#212]
E14 Cancle Bulb
ID Jm5pbvaDrH4ZjHoT  Version 1.0.3
![image](https://user-images.githubusercontent.com/32928749/100990981-68616f00-354a-11eb-9b46-9c75e696b4d8.png)

Same Bulb, same ID, same version, different config? Dont know why, but still works
E14 Cancle Bulb
ID Jm5pbvaDrH4ZjHoT  Version 1.0.3
![image](https://user-images.githubusercontent.com/32928749/100991272-b8403600-354a-11eb-8fe5-c42ac668f5d3.png)

**Comment by ultratoto14** [comment]
@DavidFFerreira i see no difference here, if you are talking about the values after the DP ids, this is just the current value of the datapoint at the time it has been setup. The only "configuration" things are the DP id, before (value: xxxxxxx).

**Comment by DavidFFerreira** [comment]
@ultratoto14 oh ok, I didnt put the other until white works lol

**Comment by ultratoto14** [comment]
Seems to be a misunderstanding. Closing for now.
