### ISSUE TITLE
Problems to discover

### ISSUE THREAD

**Issue by alrodgir** [rospogrigio/localtuya#214]
Hi, 
First my system is a raspi 3b+ with hassos 4.17

Second, recently I installed the local-tuya integration in my hassOS. But first I deleted the tuya native add-on to avoid problems with discovered devices, but this is just what I get.
In the discover windows I get this error:

`Pick one of the automatically discovered devices or ... to manually to add a device.`
`Address used for discovery is already in use. Make sure no other application is using it (TCP port 6668)`

And no devices appear on the windows :/ 
May you help me to complete delete the native tuya discovered devices? I think this is the problem, is it?

Best Regards.

**Comment by postlund** [comment]
Only one can listen on the ports used for discovery and someone else is currently doing it, likely the original tuya integration. So removing that might certainly help.

**Comment by ovid-io** [comment]
I have this issue too, the way to reproduce it is start setting up localtuya integration as new, don't add device and then any subsequent attempt to set it up will fail with above message until home assistant is restarted

**Comment by postlund** [comment]
Right, now I remember and I know why this happens. I will try to push a fix for it later.
