### ISSUE TITLE
NOT AN ISSUE: [HELP Request] - Feit Smart Dimmer Switches

### ISSUE THREAD

**Issue by afraazali** [rospogrigio/localtuya#228]
I'm currently using HA's Tuya Integration for these dimmers. I was wondering would it be possible to use LocalTuya instead? Are these dimmers compatible?

**Comment by ultratoto14** [comment]
Hi @afraazali can you use [HOWTO-get-a-DPs-dump](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump) and give full dump with let say `on`, `off`, `25%`, `75%` ?

**Comment by afraazali** [comment]
Hi @ultratoto14,

I went through the steps of setting up, https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md. I don't see the devices list on iot.tuya.com, but it does state it'll take up to 24 hours. I tried running `test.py`, but I got a `Failed to connect` error message. I used both the IP shown on the smartlife app for the device and the internal IP as shown in the router settings. However, I still don't know where to find the `localKey`.

**Comment by D33M** [comment]
After you create the API key in the Tuya API, you will need to use the `tuya-cli` tool to obtain the `localKey` and `deviceId`. This is fairly simple, but you will need to install the `npm` tool as well as the `tuya-cli`. Then just execute the command described in the docs and it will return those values in ~1 min. This action will also show you the devices on the list in the Tuya API.

`permission deny` error seems like you would got any steps in the Tuya API wrong. Please ensure that you set proper values in the `tuya-cli` tool:
```
sudo tuya-cli link  --api-key "my_api_key"  --api-secret "my_api_secret"  --schema "my_schema"  --ssid "my_wifi_name"  --password "my_wifi_password"  --region "eu"
```
It also took me 24 hours until my API key & API secret were available for me to use here.

**Comment by ultratoto14** [comment]
Also ensure that you did not forget to enable the API access:
> On the same page, click "API Group" on the left side. Change the status to Open for the following three API Groups by clicking "Apply" for each line, entering any reason, and clicking "OK": "Authorization Management", "Device Management", "Device 
> Control", "User Management", "Network Management", "Data Service" and "Device Statistics". It can take 10-15 minutes for  these changes to take effect.

**Comment by ultratoto14** [comment]
To easily have your devices in tuya, in this menu:
![image](https://user-images.githubusercontent.com/3328573/101749648-462d9b00-3ace-11eb-8352-b6f8e47a4dad.png)
When you click on Add App Account, a QR code will popup, in your tuya app, click on `+` to add a device, you will have the ability to scan a code on the upper right, then scan this code. The app will then be joined and you will have your devices listed in this tab.

**Comment by afraazali** [comment]
Hi @ultratoto14,

I double checked the API’s and all the ones listed in your comment are marked “open”. I also linked my account using the QR code, but the devices aren’t showing up in my device list on iot.tuya.com.

@D33M, do I need to run `tuya-cli link` even if I’ve linked my account via the QR code method?

Is it best to delete the devices in the smart life app and re-link them to the app?

**Comment by ultratoto14** [comment]
@afraazali So now you have a line below the Add App account and so Device quantity is set to 0 ?
If it is 0, can you reset one of your device and re register with the app ?

**Comment by afraazali** [comment]
I’ll try this today and report back my findings. I appreciate all the support.

**Comment by afraazali** [comment]
Thank you @ultratoto14! Removing the device and adding it back into the smart life app worked. It’s showing the device in the list on iot.tuya.com. I’ll put up the DPS dump, later today.

**Comment by afraazali** [comment]
Here's the dump after I ran the following command `python3 test.py DEVICE_ID INTERNAL_IP LOCAL KEY`

```
Device DEVICE_ID at INTERNAL_IP key LOCAL_KEY protocol 3.3 dev_type type_0a:
    DPS [1] VALUE [False]
    DPS [2] VALUE [160]
```

**Comment by ultratoto14** [comment]
Hi @afraazali as now you have access to DPs can you do a dump with let say on, off, 25%, 75% ?

**Comment by afraazali** [comment]
Here are the dumps for the 4 states:

```
Off:

TuyaDebug (Tuya DPs dump) [1.0.0]

Device DEVICE_ID at INTERNAL_IP key LOCAL_KEY protocol 3.3 dev_type type_0a:
    DPS [1] VALUE [False]
    DPS [2] VALUE [246]

On (100%):

TuyaDebug (Tuya DPs dump) [1.0.0]

Device DEVICE_ID at INTERNAL_IP key LOCAL_KEY protocol 3.3 dev_type type_0a:
    DPS [1] VALUE [True]
    DPS [2] VALUE [1000]

On (25%):

TuyaDebug (Tuya DPs dump) [1.0.0]

Device DEVICE_ID at INTERNAL_IP key LOCAL_KEY protocol 3.3 dev_type type_0a:
    DPS [1] VALUE [True]
    DPS [2] VALUE [250]

On (75%):

TuyaDebug (Tuya DPs dump) [1.0.0]

Device DEVICE_ID at INTERNAL_IP key LOCAL_KEY protocol 3.3 dev_type type_0a:
    DPS [1] VALUE [True]
    DPS [2] VALUE [749]
```

**Comment by ultratoto14** [comment]
So in your config, try with this configuration  a `light`

```yaml
  - host: 192.168.1.10
    device_id: xxxxxxxxxxxxxxx
    local_key: xxxxxxx
    friendly_name: Feit Smart Dimmer Switch 1
    protocol_version: "3.3"
    entities:
      - platform: light
        friendly_name: Feit Smart Dimmer Switch 1
        id: 1
        brightness: 2
        brightness_upper: 1000
```
If you use config flow, just set as showed in yaml 👍

**Comment by afraazali** [comment]
Thank you @ultratoto14, it worked. I just have the two following warnings in my logs:

```
Entity light.feit_smart_dimmer_switch_1 is requesting unset index for option color_mode
Entity light.feit_smart_dimmer_switch_1 is requesting unknown DPS index None
```

**Comment by ultratoto14** [comment]
This log is not problematic, you can deal with. I'll try to push a or for that log, happy that I helped you. 

Can you provide your product id, manufacturer, model, firmware version so that I can put the data into the wiki?

**Comment by afraazali** [comment]
Apologies, but where can I find all that information? The packaging says Feit Electric Wi-Fi Smart Dimmer.

**Comment by ultratoto14** [comment]
- Firmware can be found in the device information in the Tuya App.
- Product Key is available in Home Assistant > Configuration > Devices > Model
- You can give me a link to the device where you bought it 😄 

About your question in blocking cloud access, check the opened issues and even the PR, I saw comments about that and it's not trivial.

**Comment by afraazali** [comment]
* I've linked them in the Smart Life app and under Device Update of the switch it shows **Main Module: V3.1.4** **MCU Module: V1.0.8**
* Tuya Generic (`tebc75erlgslgpn5` is what is displayed on iot.tuya.com)
* https://www.costco.com/feit-electric-wi-fi-smart-dimmer%2c-3-pack.product.100518151.html

Thank you again.
