### ISSUE TITLE
Support of Tuya Humidifier

### ISSUE THREAD

**Issue by kombi21251** [rospogrigio/localtuya#233]
Hello!

Thanks a lot for local tuya integrations! It's working well!

I recently buy a WetAir WH-735 humidifier. Works well in HA with your integration. But there are such settings as: intensity and mode. Will there be support for climate devices in the future (https://developers.home-assistant.io/docs/core/entity/climate#set-hvac-mode)?

**Comment by kombi21251** [comment]
This is my objects for local tuya integration of humidifier.
![image](https://user-images.githubusercontent.com/62477460/102023996-dc481680-3d97-11eb-8c3b-16dfdda9456e.png)

**Comment by ultratoto14** [comment]
@kombi21251 for the missing support for let say intensity and so on, a new [service](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump#changing-value-of-a-datapoint) has been introduced that will let you set the DPs directly.
You may then use `input_select` and automation to fulfill your needs.

**Comment by kombi21251** [comment]
> @kombi21251 for the missing support for let say intensity and so on, a new [service](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump#changing-value-of-a-datapoint) has been introduced that will let you set the DPs directly.
> You may then use `input_select` and automation to fulfill your needs.
> 
> About the climate support, a PR #72 is already opened, but it seems on hold for the moment.

Thanks! It's work very well!

**Comment by Slejpnir** [comment]
> > @kombi21251 for the missing support for let say intensity and so on, a new [service](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump#changing-value-of-a-datapoint) has been introduced that will let you set the DPs directly.
> > You may then use `input_select` and automation to fulfill your needs.
> > About the climate support, a PR #72 is already opened, but it seems on hold for the moment.
> 
> Thanks! It's work very well!

Hello! Have you succeed in setting time before turn off with set_dp service?

**Comment by kombi21251** [comment]
@Slejpnir, not yet. But I am already control intensity, work mode and set humidity. Perhaps setting time before turn off also good work with set_dp service. 
![image](https://user-images.githubusercontent.com/62477460/103458532-cdf37780-4d11-11eb-928f-e5cc21892173.png)
dp's 3 and 4 – it is timer setting. 3 – in hours, 4 – in minutes. When timer is no set, then dp_3 have value 'cancel'.

**Comment by reski-rukmantiyo** [comment]
> This is my objects for local tuya integration of humidifier.
> ![image](https://user-images.githubusercontent.com/62477460/102023996-dc481680-3d97-11eb-8c3b-16dfdda9456e.png)

Hi @kombi21251 , do you mind to share your localtuya config for this?
Since I cant find Humidifier configuration in the github.

Thanks
