### ISSUE TITLE
Support for window/door open sensor

### ISSUE THREAD

**Issue by bigretromike** [rospogrigio/localtuya#257]
Hello,

I wanted to add door/window/opening sensor, but looks like im failing because its not supported.
Its very simple device.

```
{"activeTime":1597068593,"devId":"*delete*","displayOrder":0,"dpMaxTime":1608050912746,"dpName":{},"dps":{"1":false,"3":"high"},"errorCode":0,"iconUrl":"https://images.tuyaeu.com/smart/icon/ay1525749833414yotNt/92722d1b64636ed1dfe3107187643324.jpg","isShare":false,"key":"*delete*","lat":"","localKey":"*delete*","lon":"","moduleMap":{"mcu":{"cadv":"","isOnline":true,"verSw":"1.0.0"},"wifi":{"bv":"5.42","cadv":"","isOnline":true,"pv":"2.2","verSw":"1.1.1"}},"name":"sypialnia","productId":"*delete*","resptime":0,"runtimeEnv":"prod","timezoneId":"*delete*","uuid":"*delete*","virtual":false},
```
dps: 1 - open "true", close "false", 3: "high" batter, "middle" batter, ?low? battery (I dont have any with low but I have 1 with high and one with middle) and that would confirm whats inside smartlife application I can see open/close and high/medium battery, and history which is store in cloud.

**Comment by postlund** [comment]
You can add it using a `binary_sensor` for open state and a regular `sensor` for battery, should work fine. Most of these sensors are battery operated however and will go to sleep most of the time, so Home Assistant will lose connection to it and the entities become unavailable (so you don't have the state anymore). I intend to add support to keep state when connection is lost, but I haven't come around to fix that yet.

This has been reported before in #89, so I will close this as duplicate.

**Comment by bigretromike** [comment]
I tried, but it didnt connect. But I didn't know the part about device being sleep. that would explain why I didnt have them available in integration discovery. I will move onto #89 thanks
