### ISSUE TITLE
Cannot find local tuya in Configuration -> Integrations -> Add integration

### ISSUE THREAD

**Issue by alexxed** [rospogrigio/localtuya#269]
I tried latest stable and latest master, installed via hacs.

**Comment by alexxed** [comment]
![image](https://user-images.githubusercontent.com/2104927/103096939-52594280-460e-11eb-894f-58b192b328e6.png)

**Comment by alexxed** [comment]
![image](https://user-images.githubusercontent.com/2104927/103097328-8f720480-460f-11eb-918d-e2dbe3d872df.png)

**Comment by postlund** [comment]
Likely cache issue, try force-refresh.

**Comment by alexxed** [comment]
ah, now I feel dumb, thanks a lot!
