### ISSUE TITLE
How to add multiple devices

### ISSUE THREAD

**Issue by alexmorford** [rospogrigio/localtuya#273]
This may be a really stupid question, but how do you add multiple unique devices from the HA>Configuration>Integrations? I've been able to add one smart plug with multiple entities (switch, sensor, etc.), but don't see how to add another plug. I'm guessing this is really obvious, but am just missing it.

**Comment by mshuflin** [comment]
For each device, click "add integration" and select localtuya

**Comment by alexmorford** [comment]
Thanks, I had tried doing that, but got the error "Address used for discovery is already in use. Make sure no other application is using it (TCP port 6668)" both times when trying to add a second device. I rebooted HA in between, however, and was able to add another device.
