### ISSUE TITLE
Failed to set up discovery, port 6668 in use

### ISSUE THREAD

**Issue by mabusdogma** [rospogrigio/localtuya#274]
Hello, I would like to have both cloud and local control over some Tuya bulbs on Home Assistant.
But I always get this error:

`failed to set up discovery
Traceback (most recent call last):
  File "/config/custom_components/localtuya/__init__.py", line 171, in async_setup
    await discovery.start()
  File "/config/custom_components/localtuya/discovery.py", line 52, in start
    self.listeners = await asyncio.gather(listener, encrypted_listener)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1316, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [Errno 98] Address in use`

I have done a lsof -i :6668 and I get the cloud bulbs using the port...

Can I use different ports for local and cloud integrations of the same bulbs?
What can I do to have both?

**Comment by ultratoto14** [comment]
This is the port used to listen for discovery messages sent by devices. If you have this error, it means that you have something else on your home assistant host that is already listening on that port. 

A change can be made to ensure that the port can be reused but it should be made in the two programs listening to the port.

**Comment by mabusdogma** [comment]
Its probably the other Tuya, the original Tuya integration.
Could they both coexist, The local Tuya and the cloud Tuya, listening to the port somehow?
Something I should try?

**Comment by ultratoto14** [comment]
The port used for discovery are 6666 and 6667, can you do:
```sh
lsof -i :6666
lsof -i :6668
```

**Comment by mabusdogma** [comment]
`Lsof -i :6666
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qlipper 1081 myuser   12u  IPv6  37062      0t0  UDP *:6666`

Port 6667: no answer

**Comment by KTibow** [comment]
Try rebooting the host and see if that helps.

**Comment by mabusdogma** [comment]
Now I know the answer!
It's qlipper (in lxqt) who uses port 6666
I uninstalled it and replaced it with copyQ, it works fine now
