### ISSUE TITLE
Energy monitoring value for Feit Smart Plugs from Costco?

### ISSUE THREAD

**Issue by vinhdizzo** [rospogrigio/localtuya#276]
Hi,

I am new to Home Assistant, and hence, local tuya. I have some smart plugs that I would like to use with local tuya. Here is a dump of the DP's:

```
3.3 dev_type type_0a:
    DPS [1] VALUE [False]
    DPS [9] VALUE [0]
    DPS [38] VALUE [off]
```

I can confirm that DP 1 is to turn the plug on and off based on my testing. I would like to monitor energy values in order to incorporate washer and dryer notification with these plugs. It appears only DP 9 is numeric. When I plugged in a phone charger, DP 9 remains at 0.

Does this mean that these plugs do not offer energy monitoring via DP?

I assume I can go the attribute route, which is briefly explained in bullet 2 in the README page. Could someone elaborate on what `sw01` refer to from the example?

**Comment by ultratoto14** [comment]
Do you have the consumption data in the tuya app ?

**Comment by vinhdizzo** [comment]
I do not see any consumption data in the TuyaSmart App when I click on the plug. I just see on/off, schedule, and timer.

I remember adding the device as a socket in the app. Does this matter? Should I have added it as a power strip? In the Feit App, there is an actual smart plug type that I select.

Thanks.

**Comment by postlund** [comment]
DP 9 is likely for schedule (most under 10 are). Based on the DP dump I would say it doesn't support energy monitoring, but you should check what the manufacturer say about your model.

**Comment by vinhdizzo** [comment]
Thank you. No where on the box does it advertise energy monitoring. I just assumed all smart plugs have this capability. It does advertise schedules, so I think you are right on DP 9.

These are going back to the store or to my brother in law.

Thank you all.
