### ISSUE TITLE
Add supported Device

### ISSUE THREAD

**Issue by rishabmehta7** [rospogrigio/localtuya#300]
Hi 

I have a Wipro Smart RGB Batten (https://www.amazon.in/dp/B08D19X3LS/ref=twister_B08LHJ9JL3) that I was able to get working with localtuya
Below are the details. Can this be added to Wiki - Known devices? I don't think I can make a pull to Wiki

I can confirm everything seems to work.

Name | Brand | Product Key | Firmware | Type | ID(on/off) | Color Mode | Brightness | Color Temp | Color | Scene | Max Brightness | Min Brightness | Min °K | Max °K | Music Mode
Wipro 20 W Smart LED Batten (RGB) | Wipro | keyfm7948n9gxnu8 | 1.0.3 | RGBCWWW | 20 | 21 | 22 | 23 | 24 | 25 | 1000 | 29 | 2700 | 6500 | --

Rishab

**Comment by ultratoto14** [comment]
Done.

**Comment by rishabmehta7** [comment]
They link specified in Wiki, is to the non RGB one. I too can't seem to find the official link for the RGB.
Also just wondering RGBCW means RGB + Warm white + Cold white? Bcoz this has the same.

Rishab

**Comment by ultratoto14** [comment]
RGBCW for is white color => color temperature.

**Comment by ultratoto14** [comment]
Removed the link.

**Comment by rishabmehta7** [comment]
Closing for now. If I find an official link will reopen this.
