### ISSUE TITLE
(Not an error) Tuya connection issues after using LocalTuya

### ISSUE THREAD

**Issue by Od1e** [rospogrigio/localtuya#305]
Hello, I set up and hooked all of my bulbs into LocalTuya today and it works great for the most part, but I later found that when trying to control my bulbs through Alexa (Smart Life via Alexa) and the Smart Life iPhone app that many of the bulbs are unresponsive and/or marked as "Unresponsive". All of the bulbs, even when marked as unresponsive in Smart Life, are still controllable through LocalTuya. Is this a direct result of using LocalTuya with these bulbs and has any one else had this issue? Is this some sort of rate limit from messing with the Tuya IOT dev website?

**Comment by ultratoto14** [comment]
Most of the devices are supporting only one connection at a time. It means when they are used in localtuya, you cannot use the google/alexa cloud connection at the same time. You're best bet is to share the device to google/alexa from Home Assistant.

**Comment by infogramma** [comment]
I'm using LocalTuya but Alexa voice commands still work, no issues.
Devices are configured by means of the Smart Life Android app (not the Tuya app) and the Smart Life skill for Alexa.

**Comment by ultratoto14** [comment]
It depends on the different devices it's not a rule.
@Od1e can you share the device descriptions ?

**Comment by lishan89uc** [comment]
I had an issue with like this with my Feit dimmers from costco though. After re-adding them i haven't had any issues though. After readding the key changes so you have to update the localtuya settings as well

**Comment by Od1e** [comment]
@ultratoto14 I have 12 of these bulbs: https://www.amazon.com/OHLUX-Compatible-Equivalent-Multi-Color-Bulb-4PACK/dp/B07LCB3HQJ
What you originally said would also make sense, that the bulbs only support one simultaneous connection.

**Comment by ultratoto14** [comment]
@Od1e if you already have configured alexa with your Home Assistant, you can at least try to share these bulbs and see.
