### ISSUE TITLE
Devices not available after 3.2.0 upgrade

### ISSUE THREAD

**Issue by joe-sydney** [rospogrigio/localtuya#332]
My fan and blind (cover) is no longer available. Reverting to 3.1.0 works. Tried #288, but that did not work - after reboot the device was up and I could turn it on... then it went unavailable. 

Those tuya devices and Home Assistant are on separate subnets.

3.1.0 was solid for me, I just wanted the ability to set_dp.

**Comment by joe-sydney** [comment]
I had the ability to run a second HA instance on the IOT LAN (which was used to run localtuya integration) and used the Remote-Home-Assistant on the main HA to access the devices.... and this worked.

**Comment by ilbarone87** [comment]
> My fan and blind (cover) is no longer available. Reverting to 3.1.0 works. Tried #288, but that did not work - after reboot the device was up and I could turn it on... then it went unavailable.
> 
> Those tuya devices and Home Assistant are on separate subnets.
> 
> 3.1.0 was solid for me, I just wanted the ability to set_dp.

Hi, I have 4 smart plugs and i saw the same behaviour, i had to downgrade the plugs to 3.1.0 to make them work again.
Have you come up to any solution in case?
