### ISSUE TITLE
[device request] Tuya Doorbell (LSC)

### ISSUE THREAD

**Issue by Waylikemark** [rospogrigio/localtuya#395]
Dear developers,

at first thanks for your hard work for making this possible. During setup i noticed that my tuya doorbell is reconized as a device. Since it’s a doorbell it is not possible to add it though. Will there be support for this device?

link to the specific device: https://www.action.com/nl-nl/p/dummy-3003046/

**Comment by Tyrian81** [comment]
Hi ,

These can be rooted , and fully integrated into HA by doing so 
https://github.com/guino/BazzDoorbell/issues/2

**Comment by Waylikemark** [comment]
@Tyrian81 thanks! i already saw it once but the description and tutorial are a bit messy and all over the place so i did not understood everything. I will dig into this but already running into an issue on the first step. I get a login screen but don't know what to enter there. Since i can't find it any do you know by any chance if i can still control the device in the Smart Life app after rooting it?

**Comment by Tyrian81** [comment]
> @Tyrian81 thanks! i already saw it once but the description and tutorial are a bit messy and all over the place so i did not understood everything. I will dig into this but already running into an issue on the first step. I get a login screen but don't know what to enter there. Since i can't find it any do you know by any chance if i can still control the device in the Smart Life app after rooting it?

admin / admin might work, my doorbell still functions in the lsc/tuya app as well (depending on firmware version 2.9.7) continuous recording needs to be disabled , as it might overwrite the root and pspap

**Comment by Tyrian81** [comment]
depending on your firmware , i could send you some files to put on your SD card
rooting it was quite tedious indeed, but got a lot in return 
ONVIF and rtsp camera feed, doorbell push and motion via mqtt to HA

**Comment by Waylikemark** [comment]
Thanks admin/admin works (thought i tried that already, but didn't apparently)! My firmware is version 2.9.7 aswell so some files would be nice since i can't figure some things out, mostly because of the formulation in all steps. 

For continuous recording is a special cleanup.cgi file so that you don't need to turn that off if i read correctly?

**Comment by postlund** [comment]
Just as a follow-up here, is it battery powered and that's why you can't add it? Didn't quite get that from the link.

**Comment by Waylikemark** [comment]
> Just as a follow-up here, is it battery powered and that's why you can't add it? Didn't quite get that from the link.

No it has it’s own powersupply. Can be installed on an existing trafo but also has a wallplug included.

**Comment by postlund** [comment]
> > Just as a follow-up here, is it battery powered and that's why you can't add it? Didn't quite get that from the link.
> 
> No it has it’s own powersupply. Can be installed on an existing trafo but also has a wallplug included.

Ok, so what happens when you try to add it?

**Comment by Waylikemark** [comment]
> > > Just as a follow-up here, is it battery powered and that's why you can't add it? Didn't quite get that from the link.
> > 
> > 
> > No it has it’s own powersupply. Can be installed on an existing trafo but also has a wallplug included.
> 
> Ok, so what happens when you try to add it?

I get an error message in config flow. I cannot reproduce it since i can't figure out the new way of collecting the local key. I looks like i need to reset them?

**Comment by Waylikemark** [comment]
> > > Just as a follow-up here, is it battery powered and that's why you can't add it? Didn't quite get that from the link.
> > 
> > 
> > No it has it’s own powersupply. Can be installed on an existing trafo but also has a wallplug included.
> 
> Ok, so what happens when you try to add it?

Figured it out the error is: Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.

**Comment by postlund** [comment]
Right, that's tricky with the protocol. It's non-trivial to extract the datapoints because they seem to have manufacturer specific oddities.
