### ISSUE TITLE
Add new device

### ISSUE THREAD

**Issue by trancefreak77** [rospogrigio/localtuya#408]
How can I add a new device to the local tuya integration? There is no "Add Device" button in the devices list of the local tuya integration. Do I have to always add a new local tuya integration when adding a device?

**Comment by postlund** [comment]
To add a new physical device, just use "Add Integration" under Configuration -> Integrations. Pick the device from the list (based on IP or device if if you happen to know that). If you want to add a new entity, e.g. a switch or sensor, to an existing device, do the same thing but pick the existing device from the list (you should see them name of exiting devices in the list).
