### ISSUE TITLE
Tuya no longer supports Linking devices by apps

### ISSUE THREAD

**Issue by socaljr53** [rospogrigio/localtuya#421]
The Tuya developer documentation has been updated and as of March 24, 2021, they no longer support linking devices by product or apps.

https://developer.tuya.com/en/docs/iot/open-api/user-guide/managing-devices/link-devices?id=Ka471nu1sfmkl#title-3-Link%20devices%20by%20apps

**Comment by postlund** [comment]
I'm not sure I understand what this means in practice (not really my area), can you elaborate?

**Comment by robertkalinowski** [comment]
This is not true, it is enough to read the tyua documentation carefully.
"Note: This topic only applies to all projects created before March 24, 2021 (the project type is marked as Others) and all smart home projects created after March 24, 2021.
"

That simply means that to have linking devices by product or app enables you need to mark project when creating as "smart home" project and not any other type.
