### ISSUE TITLE
Disable discovery

### ISSUE THREAD

**Issue by Mallinanga** [rospogrigio/localtuya#431]
Hello...

I was wondering if there is a way to disable local tuya discovery once you have everything setup and working.

It's not something critical, but I guess it would be nice to have a "quieter" network for things you don't need.

**Comment by postlund** [comment]
Devices broadcast their presence when no one is connected to them (generally). Discovery from our perspective is just listening to these broadcasts, we never send anything ourselves. So assuming everything works as expected and you have added all your devices to Home Assistant, there should be no broadcasts. I believe this is firmware specific though (manufacturers can change how this works), so if they still send broadcasts there's nothing more we can do.

**Comment by Mallinanga** [comment]
I see.
Thanks for the quick and clear answer :)
