### ISSUE TITLE
localtuya missing from HA Integrations

### ISSUE THREAD

**Issue by iJuiceman** [rospogrigio/localtuya#436]
-->
## The problem
I wanted to add localtuya to my HA setup.  Following the setup, I can see the localtuya in HACS and add it sucessfully.  However the next step in the instructions mentions adding it under  Configuration - Integration and pressing the "+" button to create a new Integration.  The problem is that local Tuya is not in the listed integrations.  I can only see the Tuya integration.  I have rebooted and checked and double checked.  I have not tried adding devices in YAML, as I have over 15 Tuya devices

## Environment

- Localtuya version:3.2.2 (HACS)  
- Last working localtuya version N/A (if known and relevant): 
- Home Assistant Core version: core-2021.4.0 
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [x] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1.  Configuration - Integration and pressing the "+" button to create a new Integration, see a list of integrations available, but no local tuya.  Tried searching local and tuya, but nothing listed
2. It also does not appear in: https://www.home-assistant.io/integrations/#search/local
3.

## Provide Home Assistant taceback/logs

```txt

```

**Comment by kingwap99** [comment]
I have the same issue with you, 
just try to reboot the host or restart ha one or two times may solve it.
or you can go back to core-2021.3.4 to avoid this issue.

**Comment by postlund** [comment]
It's a cache issue in your browser. Force-refresh and it will appear again.

**Comment by kingwap99** [comment]
> It's a cache issue in your browser. Force-refresh and it will appear again.

Is this cache issue relate to core-2021.4.0 only ?
Because it never happened before.

**Comment by postlund** [comment]
It's a general thing. We get these kinds of issues reported every now and then.

**Comment by iJuiceman** [comment]
Hi, Thanks for the quick response.  It was cache and I can now see it.  Sorry for the noob issue.
