### ISSUE TITLE
Switch not reporting state

### ISSUE THREAD

**Issue by tungmeister** [rospogrigio/localtuya#488]
Hi,
I've just started using the integration and added a single wall switch that I've purchased for testing purposes. I've been able to integrate it as a switch however state isn't being reported. the switch works and I can turn the lights on and off however the state doesn't update and always goes back to off in Home Assistant. Any suggestions?

**Comment by TheByteStuff** [comment]
What entities did you add?  I had the same problem when configuring an Evalogik switch until I realized that there were two entities available.  I am thinking one controlled the action and the other is the state.  Anyhow, I encountered the same situation where I could toggle lights on/off but the status in HA always went to "off".  Once I configured both entities state was held.  I haven't had time yet to go back and figure out which entity is which or more appropriately which entity is "switch".

**Comment by tungmeister** [comment]
could you share your exact config and I'll give it a go?

**Comment by TheByteStuff** [comment]
For my switch, I have two entities - IDs 1 & 7.  I added both.  I think ID1 is the status of the switch (true/false for on/off) and ID7 is maybe to indicate the switch itself as on/off.   What entity types do you have available and what are the options (i.e. IDs?)


![LocalTuya_CoachLight_EntityType](https://user-images.githubusercontent.com/19675643/119557232-e8d09200-bd6d-11eb-9b7f-3f6f326584a2.png)

![LocalTuya_CoachLight_AddEntities](https://user-images.githubusercontent.com/19675643/119557413-28977980-bd6e-11eb-9588-af269de9a0e3.png)

![LocalTuya_CoachLight_AddEntities_1TrueFalse_blurred](https://user-images.githubusercontent.com/19675643/119557242-ebcb8280-bd6d-11eb-9cf7-c371ffcd73ad.png)

![LocalTuya_CoachLight_AddEntities_7_0or1_blurred](https://user-images.githubusercontent.com/19675643/119557250-eec67300-bd6d-11eb-90a9-8aef85977fce.png)

**Comment by tungmeister** [comment]
thanks, this solved my issues
