### ISSUE TITLE
LocalTuya支持添加涂鸦zigbee单火线墙壁开关么？

### ISSUE THREAD

**Issue by oliver-ok** [rospogrigio/localtuya#523]
LocalTuya集成修改config文件添加zigbee单火线开关没能成功搞定。
LocalTuya可以支持添加Zigbee单开单火线墙壁开关吗？
这个开关通过HA自带的Tuya集成云端添加可以。但是想要局域网控制Tuya集成搞不定了。

**Comment by lishan89uc** [comment]
zigbee的话应该是用 zha, deCONZ, 或者 zigbee2mqtt 来加入HA吧? Localtuya 是拿来控制直接连接wifi 的开关. 不过我也没法肯定localtuya有没有办法控制tuya 盒子下的zigbee产品. 你可以尝试拿 [HOWTO-get-a-DPs-dump](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump) 的[tuyadebug.tgz](https://github.com/rospogrigio/localtuya/raw/master/tuyadebug.tgz) 来看看有没有 "数据点"datapoint (DP)
不好意思我不是电脑工程师, 中文也不是太好请多多包涵.

**Comment by FrostZhang** [comment]
我目前也在做这件事。可以确定的是支持一个网关下控制一个开关。设定方法key值不便。id换成开关的c_id，host仍然是网关的地址。这样就可以正常工作了。

**Comment by rulaiking** [comment]
我用过零火线的4开，用Z2M解决不了，准备用小米的双模解决，不知道可不可以。

**Comment by rospogrigio** [comment]
I have introduced Zigbee support in PR #1493,  if anybody wants to test it and provide feedback, please comment in the PR.

**Comment by rulaiking** [comment]
你的文件已收到，谢谢
