### ISSUE TITLE
Can't integrate virtual device created in Tuya IoT platform

### ISSUE THREAD

**Issue by KirkKirk** [rospogrigio/localtuya#533]
I created a virtual switch in Tuya IoT platform and I would like to integrate it in Home Assistant.
I can see it as a discovered device but I can't integrate it.
I can do it if I use Tuya Smart integration, but I prefer to use LocalTuya integration.
Is there a procedure for how to do it?

**Comment by vmartinv** [comment]
Correct me if I'm wrong but the idea of LocalTuya is that it's local, it doesn't connect to the Cloud. Virtual devices are inherently located in the cloud right? You need to use the Tuya integration for that. Why do you need this exactly? I think is better to create virtual switches inside Home Assistant directly.

**Comment by KirkKirk** [comment]
You were right. Been busy and last week when I get back working on my HA I used your advance and it all is good now.
Thanks
