### ISSUE TITLE
Would love to support the implementation of new energy-meters

### ISSUE THREAD

**Issue by thrhymes** [rospogrigio/localtuya#550]
i would love to get the new emylo tuya energy meters working...

older (2years) energy-meters from emylo gave back the following status:

```
"status": [
      {
        "code": "switch_1",
        "value": true
      },
      {
        "code": "add_ele",
        "value": 247750
      },
      {
        "code": "cur_current",
        "value": 0
      },
      {
        "code": "cur_power",
        "value": 0
      },
      {
        "code": "cur_voltage",
        "value": 2258
      }
    ],
```

but the new ones give back data with nested but somehow escaped json
```
"status": [
      {
        "code": "forward_energy_total",
        "value": 63
      },
      {
        "code": "phase_a",
        "value": "{\"electricCurrent\":0.261,
                   \"power\":0.024,
                   \"voltage\":226.4
                   }"
      },
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "alarm_set_2",
        "value": "[
                     {\"alarmCode\":\"overcurrent\",
                      \"doAction\":false,
                      \"threshold\":\"60\"},
                      {\"alarmCode\":\"ammeter_overvoltage\",
                      \"doAction\":false,\
                      "threshold\":\"264\"},
                    {\"alarmCode\":\"under_voltage\",
                    \"doAction\":false,
                    \"threshold\":\"150\"}
                   ]"
      },
      {
        "code": "meter_id",
        "value": "111111111111"
      }
    ],
```

i looked, but i could not find the right spot for the code to go to parse out and associate the values with HA entities

and maybe someone could help me get with findig that code on my home assitant installation. it seems i cannot find anything where i expected it to be.,..

**Comment by thrhymes** [comment]
ok, i played around with json-parsing and could not get any of the usual modules to parse that j*#?son 

the following worked like a charme
```
import re 
power= re.findall(r'(power).:(\d+)',fuglyJason)   # where i filled the string with the complete result-string
print ("power: " + power[0][1] + " W") # There is the power value
```

for more data extraction we could go line by line....

but still... where do i put that stuff to associate the read values with sensor-entities?

**Comment by thrhymes** [comment]
Thought some more about it...

in pytuya in _decode_payload we would either have to fix the faulty json or in the case a json-loads fails create a new valid json with the dps fixed for what localtuya can work with...

but since sensors will get more and more advanced and i guess we will see more and more "dirty" json, how about an adaptive factory, where - if json loads fails - you can look`into "product_name" to decide how to parse the result-string, before giving up?

there could be a jason-file with a list of "product_name":"parser.py" that we can extend for each new sensor or switch that comes along...

i wuld love to play around with that... i am in the process of putting together a staging-pi-home-assistant... but i still cannot find loacaltuya in the pi's directory-structure....

**Comment by thrhymes** [comment]
Analysing the code i finally found my error of thought... 

still i think the dps-model... not the best way to parse that kind of data...

**Comment by mwkchan** [comment]
I am at the same position as you, did you find any solution?

**Comment by thrhymes** [comment]
no sorry... corona hit the fan , so no time for that
