### ISSUE TITLE
Integration missing after installation

### ISSUE THREAD

**Issue by UsefulVid** [rospogrigio/localtuya#654]
[According to the readme](https://github.com/rospogrigio/localtuya#option-two-using-config-flow) I should be able to see the integration "localtuya".

`Start by going to Configuration - Integration and pressing the "+" button to create a new Integration, then select LocalTuya in the drop-down menu. Wait for 6 seconds for the scanning of the devices in your LAN. Then, a drop-down menu will appear containing the list of detected devices: you can select one of these, or manually input all the parameters.`

This is not the case:
![grafik](https://user-images.githubusercontent.com/39967070/145715950-2e4fa583-34ab-4caa-8b40-0f78fa5e5dab.png)

Installation method:
![grafik](https://user-images.githubusercontent.com/39967070/145715961-7dda5684-4ced-4363-87c4-fdaf8e32dd2a.png)

Home Assistant:
![grafik](https://user-images.githubusercontent.com/39967070/145715989-44d54d88-0484-413b-92cc-69947f5174f9.png)

Did I miss something? I already restarted HA.

**Comment by fuatakgun** [comment]
There is a browser cache for integrations page, try with an incognito mode or clean cookies

**Comment by UsefulVid** [comment]
This may be it :)
All of a sudden it appeared.

**Comment by ThomasCr** [comment]
so this can be closed?
was locking like your own fault...
