### ISSUE TITLE
Not appearing into intergrations

### ISSUE THREAD

**Issue by djandrew2005** [rospogrigio/localtuya#708]
I installed locatuya using HACS but I can't add a device intergrations. I have intalled the latest version and I have restarted home assistant after download

**Comment by MHillyer** [comment]
Click Add Integration, when the list pops up do a hard refresh of the web page, that usually makes a new HACS integration appear for me.

**Comment by Aviad1976** [comment]
Click Add Integration, when the list pops up do a hard refresh (Ctrl + F5)

**Comment by Drumdevil** [comment]
> Click Add Integration, when the list pops up do a hard refresh of the web page, that usually makes a new HACS integration appear for me.

That worked for me, thanks!
