### ISSUE TITLE
Missing scaling factor in Climate in v3.4.0

### ISSUE THREAD

**Issue by accma2** [rospogrigio/localtuya#709]
There is no scaling factor when configuring Climate, so it displays wrong values.

v3.4.0

![imagen](https://user-images.githubusercontent.com/73192304/150840583-1b23ae64-7109-451b-ba52-6c76ed761245.png)

**Comment by Daandeve** [comment]
Hi,
I found the solution for you problem you must fill the `Precision` and `Target Precision` fields in the config of the device

**Comment by dmkjr** [comment]
Curious, what thermostats are you all using with LocalTuya?

**Comment by accma2** [comment]
> Hi, I found the solution for you problem you must fill the `Precision` and `Target Precision` fields in the config of the device

Thank you!!!! It worked!

> Curious, what thermostats are you all using with LocalTuya?

I'm using this one: https://www.amazon.es/gp/product/B089SKQLKK/

It was cheaper before.
