### ISSUE TITLE
Fan speed not working anymore 

### ISSUE THREAD

**Issue by Gitspecial** [rospogrigio/localtuya#727]
Since the last update, Fan speed control stopped working, used to work fine till last version.

**Comment by 4hal9k** [comment]
Same here..
Not sure how to resolve this error...

Exception in _update_handler when dispatching 'localtuya_ebdfd264e5419f91b9ctd': ({'1': True, '2': 0, '3': 'level_2', '101': 0},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 281, in _update_handler self.status_updated() File "/config/custom_components/localtuya/fan.py", line 235, in status_updated self._speed_range, int(current_speed) ValueError: invalid literal for int() with base 10: 'level_2'
Exception in _update_handler when dispatching 'localtuya_ebdc639bb3264bdb6sqyy': ({'1': True, '2': 0, '3': 'level_1', '101': 0},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 281, in _update_handler self.status_updated() File "/config/custom_components/localtuya/fan.py", line 235, in status_updated self._speed_range, int(current_speed) ValueError: invalid literal for int() with base 10: 'level_1'
Exception in _update_handler when dispatching 'localtuya_ebdc639bb3264bdb6sqyy': ({'1': True, '2': 0, '3': 'level_3', '101': 0},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 281, in _update_handler self.status_updated() File "/config/custom_components/localtuya/fan.py", line 235, in status_updated self._speed_range, int(current_speed) ValueError: invalid literal for int() with base 10: 'level_3'
Exception in _update_handler when dispatching 'localtuya_ebdc639bb3264bdb6sqyy': ({'1': True, '2': 0, '3': 'level_4', '101': 0},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 281, in _update_handler self.status_updated() File "/config/custom_components/localtuya/fan.py", line 235, in status_updated self._speed_range, int(current_speed) ValueError: invalid literal for int() with base 10: 'level_4'
Exception in _update_handler when dispatching 'localtuya_ebdc639bb3264bdb6sqyy': ({'1': False, '2': 0, '3': 'level_1', '101': 0},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 281, in _update_handler self.status_updated() File "/config/custom_components/localtuya/fan.py", line 235, in status_updated self._speed_range, int(current_speed) ValueError: invalid literal for int() with base 10: 'level_1'

**Comment by jeeshofone** [comment]
Same here - and [here](https://github.com/rospogrigio/localtuya/issues/724)

**Comment by ratava** [comment]
Reconfigure the device and use the fan speed integer not levels.

**Comment by Gitspecial** [comment]
Yes, working with speed integer, Thanks

**Comment by nathbullen** [comment]
> Reconfigure the device and use the fan speed integer not levels.

I've got the same issue but the DP for my fan still shows low/med/high even when I try and set it up with integers - which causes the fan to not respond to HA. I know I'm doing something wrong but not sure what - any help would be greatly appreciated!

**Comment by Gitspecial** [comment]
> > 
> 
> Sorry, need help. How to reconfigure using speed integer.. Please help..

<img width="215" alt="image" src="https://user-images.githubusercontent.com/87970425/165389019-354904af-9ac8-4658-8b21-7c6c303beaed.png">
