### ISSUE TITLE
Question/Advice: Setting up tuya device as local only

### ISSUE THREAD

**Issue by UrZdcw9** [rospogrigio/localtuya#732]
Wondering if you have any advice on firewall port rules to block tuya devices communicating with the cloud.

I have tried blocking the ports listed here; in addition to the port 53 (DNS).

https://developer.tuya.com/en/docs/iot-device-dev/tuya-gateway-link-sdk-faq?id=K9dud6eqsk64o

These are ports 8883, 6667, 6668, 6669, 443, 6681, 6608, and 6682. To no avail.

Has anyone had any success?

**Comment by PeteRager** [comment]
The easiest way is to put a block rule on the source ip.  For me, it's on 192.168.40.102, so I just block all protocols from that source address.  I'm using pfSense.

**Comment by UrZdcw9** [comment]
Thanks @PeteRager,

I've tried a couple of different things.  Have been getting two different types of errors:

1)Connect call failed ('10.50.50.147', 6668)
2) the other which i dont have a copy of at the moment said something about not being in UTF-8.


Any ideas?

**Comment by PeteRager** [comment]
Firewall Config is very router specific.  What are you using?

**Comment by UrZdcw9** [comment]
Hey @PeteRager,

I run some unifi gear.  have a main network and a vlan for devices that i want to set as local only.

I've been playing with the lan in rules that can prevent local devices from looking up a DNS (port 53) which works.  but when i extend the rule to block anything further i run into issues - the devices show as offline on the tuya IOT platform; which is good.  but they show as unavailable via home assistant... obviously not good.

**Comment by UrZdcw9** [comment]
@PeteRager - ignore the above.

i solved this by allowing local in traffic to Home Assistant IP and then blocking everything else.  works a treat
