### ISSUE TITLE
Bluetooth Gateway - Connect To Gateway Failed

### ISSUE THREAD

**Issue by mking42** [rospogrigio/localtuya#746]
I was hoping to test the zigbee gateway functionality that is being worked on but I am having trouble connecting to the gateway itself. I have a bluetooth gateway but should work in the same way (with sub devices).
I have installed a fork via HACS of local Tuya that has the current gateway support (https://github.com/knifehandz/localtuya).

@rospogrigio @knifehandz

**General Info**

I can ping the gateway fine.
The gateway and down lights have been added to the Smart Life app and working there. These devices are linked to a Tuya IOT project.
I have removed the gateway from smart life. No change.
I closed the smart life app. No change.

I tried to manually add the gateway via the integrations UI but same error occurs.
Device is not detected automatically either.

I can see the devices under the integrations but due to the failed connection, devices show as unavailable.
<img width="283" alt="image" src="https://user-images.githubusercontent.com/30427133/153702097-f32af60a-b834-4629-8ab9-3805ac124fd4.png">
<img width="675" alt="image" src="https://user-images.githubusercontent.com/30427133/153702122-3f072ffd-b3a1-433f-95d3-e87f0ae4fbd1.png">

**Snippet from Configuration.yaml**

localtuya:
  - host: GATEWAY_IP_ADDRESS
    device_id: aaaaaaaa
    local_key: xxxxxxx
    friendly_name: Lucci Bluetooth Gateway
    protocol_version: "3.3"
    is_gateway: true
    
  - parent_gateway: aaaaaaaa # This tells it should be treated as a sub-device
    device_id: bbbbbbb # The Client ID (cid) of the sub-device
    friendly_name: Kitchen Downlight 1
    entities:
      - platform: light
        friendly_name: Kitchen Downlight 1
        id: 1

logger:
  default: warning
  logs:
    custom_components.localtuya: debug

**HA LOG ENTRY**

> 2022-02-12 17:10:14 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-02-12 17:10:14 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-02-12 17:10:36 DEBUG (MainThread) [custom_components.localtuya.discovery] Listening to broadcasts on UDP port 6666 and 6667
> 2022-02-12 17:10:36 DEBUG (MainThread) [custom_components.localtuya.common] [bf4...lel] Connecting to gateway IP_ADDRESS
> 2022-02-12 17:10:36 ERROR (MainThread) [custom_components.localtuya.common] [bf4...lel] Connect to gateway IP_ADDRESS failed
> Traceback (most recent call last):
> File "/config/custom_components/localtuya/common.py", line 310, in _make_connection
> self._interface = await pytuya.connect(
> File "/config/custom_components/localtuya/pytuya/__init__.py", line 799, in connect
> _, protocol = await loop.create_connection(
> File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
> raise exceptions[0]
> File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
> sock = await self._connect_sock(
> File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
> await self.sock_connect(sock, address)
> File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
> return await fut
> File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
> raise OSError(err, f'Connect call failed {address}')
> ConnectionRefusedError: [Errno 111] Connect call failed ('IP_ADDRESS, 6668)
> 2022-02-12 17:10:37 DEBUG (MainThread) [custom_components.localtuya.light] [bf4...7nn] Adding light.kitchen_downlight_1 with configuration: {'platform': 'light', 'friendly_name': 'Kitchen Downlight 1', 'id': 1, 'color_temp_min_kelvin': 2700, 'color_temp_reverse': False, 'brightness_upper': 1000, 'color_temp_max_kelvin': 6500, 'music_mode': False, 'brightness_lower': 29}
> 2022-02-12 17:10:42 DEBUG (MainThread) [custom_components.localtuya.common] [bf4...7nn] Connecting to sub-device bf4a46b52fb2c6cb1bo7nn via bf4098743f20acf3abmlel
> 2022-02-12 17:10:42 DEBUG (MainThread) [custom_components.localtuya.common] [bf4...7nn] Dispatching request request_add to gateway with content {'dps': {1: None}}
> 2022-02-12 17:11:05 DEBUG (MainThread) [custom_components.localtuya.common] [bf4...7nn] Request request_add exceeded maximum retries

**Comment by knifehandz** [comment]
@mking42 thanks for trying this out, do note it is still a work in progress even for Zigbee gateways :)

I must let you know that I've been doing this by trial and error, and am by no means an expert in Tuya gateway stuff, nor HA stuff.

Error 111 usually means either the IP or the port to connect is incorrect / unreachable. From your messages I think you already know networking quite well, is it possible for you to capture the communication between Smart Life app and the gateway?

From experience, there is no need to remove things from Smart Life, and it's a pain once done because your local key will change.

**Comment by mking42** [comment]
Thanks for the reply. I'll see if I can setup a device with wireshark to intercept traffic between HA & the BLE gateway.
Do you have an example of an API end point request the gateways use? I could try to send a request to the device API directly and read the traffic that way.

The results from a nmap scan on the device return conn refused on all ports.
"Starting Nmap 7.92 ( https://nmap.org ) at 2022-02-14 11:42 AEST
Nmap scan report for DEVICE_NAME (IP ADDRESS)
Host is up (0.0043s latency).
All 1000 scanned ports on DEVICE_NAME (IP ADDRESS) are in ignored states.
Not shown: 1000 closed tcp ports (conn-refused)"

I will work further to try and isolate the issue.
If I have time, I will setup a different network to see if I can replicate the issue. I don't believe it is my network controller causing issue but I need to eliminate it still.

I have also reached out to Tuya to get some insight as to why the "Check Device Network" function for the gateway returns an error, yet, it can be controlled via Smart Life without issues.

**Comment by knifehandz** [comment]
Tuya devices listen on TCP 6668 locally for their own protocol, with an encrypted JSON payload. I do have a test script that I use to test out pytuya when modifying it, will attach it here when I get back home.

Can you check if 6668 on your Bluetooth gateway is open?

**Comment by mking42** [comment]
That would be great. I'd love to give it a try.

I have only the nmap scan which says that port 6668 is closed (may be a false read due to other issues though).

"Starting Nmap 7.92 ( https://nmap.org ) at 2022-02-14 18:36 AEST
Nmap scan report for DEVICE_NAME (DEVEICE_IP)
Host is up (0.079s latency).

PORT     STATE  SERVICE
**6668/tcp closed irc"**

**Comment by knifehandz** [comment]
Hmm, if port 6668 is not open, there's a chance either it doesn't work on the standard Tuya port or it doesn't support local connections at all. Apart from network problems (which is rare if in the same L2 subnet), I do know some vendors choose to go cloud only.

Anyhow, please see attached the test script. It's a very basic and rough one.
[pytuya_test.zip](https://github.com/rospogrigio/localtuya/files/8062986/pytuya_test.zip)


What you are interested in is pytuya_test.py:
![image](https://user-images.githubusercontent.com/9383052/153920865-ce475a7f-7363-42f4-b6db-877a50b0386f.png)


Fill in details under GATEWAY and SUB_DEVICE and you should be good to run `python (or python3) pytuya_test.py`

Do note, if 6668 is not open, it might not be worth your time to try this script out as this connects to 6668 of the gateway.

**Comment by JerryShiruiYan** [comment]
Hi @knifehandz ,

I installed same version of LocalTuya. I am using a Kogan (Tuya) Bluetooth Mesh Gateway and A Bluetooth Mesh Light. I have cheked that port 6668 is open. When I was tring to add the gateway it is showing "Failed to authenticate with device. Verify that device id and local key are correct.". When I check the error log, it shows below. 

> 2022-03-30 13:02:55 ERROR (MainThread) [custom_components.localtuya.pytuya] [bfd...0ng] Failed to get status: Expecting value: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 629, in detect_available_dps
>     status = await self.status()
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 532, in status
>     status = await self.exchange(ACTION_STATUS)
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 506, in exchange
>     payload = self._decode_payload(msg.payload)
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 706, in _decode_payload
>     return json.loads(payload)
>   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

If I added both the gateway and led light in configuration yaml, it shows the led light is not available.
I added the gateway in configuration.yaml. Then try to add the light. It shows me the timeout error.

> 2022-03-30 13:09:28 ERROR (MainThread) [custom_components.localtuya.config_flow] Unexpected exception
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
> await fut
> asyncio.exceptions.CancelledError
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
> fut.result()
> asyncio.exceptions.CancelledError
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
> File "/config/custom_components/localtuya/config_flow.py", line 406, in async_step_basic_sub_device_info
> self.dps_strings = await validate_input(self.hass, user_input)
> File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
> detected_dps = await interface.detect_available_dps(data[CONF_DEVICE_ID])
> File "/config/custom_components/localtuya/pytuya/__init__.py", line 610, in detect_available_dps
> status = await self.status(cid)
> File "/config/custom_components/localtuya/pytuya/__init__.py", line 528, in status
> status = await self.exchange(ACTION_STATUS, cid=cid)
> File "/config/custom_components/localtuya/pytuya/__init__.py", line 497, in exchange
> msg = await self.dispatcher.wait_for(seqno)
> File "/config/custom_components/localtuya/pytuya/__init__.py", line 273, in wait_for
> await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
> File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
> raise exceptions.TimeoutError() from exc
> asyncio.exceptions.TimeoutError

May you give me some idea what is happening and how to further debug it?

Thanks a lot

**Comment by knifehandz** [comment]
Hi @JerryShiruiYan,

I am not really too sure yet what's causing this error, will try to understand the relationship between these error messages and the code.

**Comment by mking42** [comment]
I have since purchased a different Bluetooth Gateway and this one has an open port!
So, this confirms that the Bluetooth Gateway (Lucci brand) I had does not support local connections.

Thanks for everyones help trying to get to the bottom of the issue.
