### ISSUE TITLE
4 speed ceiling fan/light dimmer and an air purifier..

### ISSUE THREAD

**Issue by ThomasADavis** [rospogrigio/localtuya#75]
I guess I get to break things.

I have a combo light/fan controller also, that's tuya based.

It is a 4 speed controller, and a can dim the light.

Code|Type|Values
--------|------|---------
switch|Boolean|{true,false}
fan_speed|Enum|{"range":["1","2","3","4"]}
light|Boolean|{true,false}
bright_value|Integer|{"min":10,"max":1000,"scale":0,"step":1}

Note that is a 4 speed controller,  and not 3.  So 'low', 'medium', 'high' does not fit.

Here's what is actually discovered:
![fan-controller](https://user-images.githubusercontent.com/12158973/95693933-f58be580-0be3-11eb-996d-10e7d1635c7a.png)

Now, to really mess this up.. I also have a air purifier, that's tuya based.

iot-tuya says this for it:

code|type|values
------|--|--
switch|boolean|	true,false
lock|	boolean| true,false
light|boolean|true,false
countdown|enum|range:["cancel"]

but this is so wrong..
![air-purifier](https://user-images.githubusercontent.com/12158973/95693842-52d36700-0be3-11eb-9aef-349efcea63cf.png)

It shows the 4 filters, the fan speed (low/medium/high/auto), power on/off, child lock, air quality, and few other things.

I am planning on digging around more in the code for this.. once I figure out how to do development work in it.

One of the questions I have - is an air purifier a fan, or something else in home-assistant?

**Comment by ThomasADavis** [comment]
the dp's:

1 = fan power
2 = fan speed (level1/level2/level3/level4)
3 = light power
10 = brightness (0-1000)
101 - countdown timer fan
103 - countdown timer light
105 - dimming range
106 - dimmer mode.  mode1/mode2/mode3 

so, for the air purifier:

1 = power
2 = fan speed (low/mid/high/auto)
7 = sleep mode (?)
8 = ?
19 = ?
22 = air quality (good/moderate/bad)
101 = ?
102 = Pre-filter life
103 = charcoal filter life
104 = Activated carbon filter life
105 = True HEPA filter life

more as I figure things out.

**Comment by ThomasADavis** [comment]
```2020-10-11T18:25:51.202906924-07:00 stderr F 2020-10-12 01:25:51 ERROR (SyncWorker_7) [homeassistant.util.logging] Exception in _update_handler when dispatching 'localtuya_00523543d8bfc0d3e0a3': ({'devId': '00523543d8bfc0d3e0a3', 'dps': {'1': True, '4': 'low', '7': False, '8': True, '19': 'cancel', '22': 'good', '101': False, '102': 43, '103': 43, '104': 43, '105': 43}},)
2020-10-11T18:25:51.203101834-07:00 stderr F Traceback (most recent call last):
2020-10-11T18:25:51.203134074-07:00 stderr F   File "/config/custom_components/localtuya/common.py", line 198, in _update_handler
2020-10-11T18:25:51.20315806-07:00 stderr F     self.status_updated()
2020-10-11T18:25:51.203177096-07:00 stderr F   File "/config/custom_components/localtuya/fan.py", line 104, in status_updated
2020-10-11T18:25:51.203198551-07:00 stderr F     elif self._status["dps"]["2"] == "1":
2020-10-11T18:25:51.203219569-07:00 stderr F KeyError: '2'
2020-10-11T18:25:51.20325473-07:00 stderr F 
^C
```
yea, it doesn't return numbers, it is the actual status as text. (ie, 'low', 'high', 'auto')

**Comment by ThomasADavis** [comment]
So, more notes:

1) local_tuya assumes fan is id 2.  I have id 3 and id 4.
2) local_tuya assumes numbers are returned, not strings.  I get strings on the air purifier, numbers on the 4 speed fan.
3) home-assistant currently has only 3 speeds for fans - low, medium, high.  so one of the speeds on my 4 speed controller needs to be mapped out, and the 'auto' setting on the air purifier either mapped or ignored to something else.

I'll work on a PR to try and fix some of these problems.

**Comment by postlund** [comment]
@ThomasADavis Did your fan PR fix/implement this issue so we can close it?

**Comment by ThomasADavis** [comment]
Yea, this all works now.

Closing.
