### ISSUE TITLE
working, but unable to add more devices

### ISSUE THREAD

**Issue by Stooovie** [rospogrigio/localtuya#775]
## The problem

I have LocalTuya already set up and working with five devices, but am totally unable to add (=get the Local key) for a new one. I have 0 devices in Cloud/Development/Devices (any of the below tabs). I cannot change my Datacenter from the Central European one (and I'm pretty sure I have used this one for my done and working devices).

tuya-cli wizard tells me "There was an issue fetching that device. Make sure your account is linked and the ID is correct.", clientID, secret and virtual IDs are entered correctly.

I don't want to mess up my working devices, so I'm not creating and re-linking new projects with different data center unless i'm sure that would help. Please advise.

## Environment

- Localtuya version: 3.4.0
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version: 2022.3.6
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ?

**Comment by maxfield-allison** [comment]
I dont think you need to create a new project. for what its worth i was experiencing odd behavior with the iot.tuya.com site earlier today. seems like they may have something going on in the back end causing other issues. I'd give it some time and try again. also make sure you have pop up blockers disabled before you try checking devices in the cloud console.

**Comment by Stooovie** [comment]
thank you but it's like this for a week now, I can't even find my existing devices (that do continue to work both locally and via Smart Life app). It might be an user error but I was able to first make this work rather easily so I don't think I would screw up so royally :)

**Comment by Stooovie** [comment]
So of course I DID screw up royally, it's a different Tuya account 🤦🏻‍♂️ Thank you and sorry for my ineptitude 🤣
