### ISSUE TITLE
Adding devices when on an different vlan to home assistant

### ISSUE THREAD

**Issue by psyciknz** [rospogrigio/localtuya#778]
## The problem

I can't discover the two Kogan devices I have.  Nor manually configure them.  Looking at the home assistant logs I see a timeout error. 

I did allow port 6666/6667 out from the iot vlan.  But no difference.
## Environment

- Localtuya version:  
Master from today. 

- Last working localtuya version (if known and relevant): 
N/a

- Home Assistant Core version:  
2022.3.5

- [] Are you using the Home Assistant Tuya Cloud component ? 

Yes

- [] Are you using the Tuya App in parallel ? 
No.

## Steps to reproduce

1. 
2. 
3.

## Configuration `configuration.yaml` or `config_flow`

```

localtuya:
  - host: 192.168.100.47
    device_id: xxxxx
    local_key: xxxxxx
    friendly_name: Kogan-01
    protocol_version: "3.1"
    #scan_interval: # optional, only needed if energy monitoring values are not updating
    #  seconds: 30 # Values less than 10 seconds may cause stability issues
    entities:
      - platform: binary_sensor
        friendly_name: Kogan-01 Plug Status
        id: 1
        device_class: power
        state_on: "true" # Optional
        state_off: "false" # Optional

```
I tried one via config flow as well.  It got the same error. 

## Provide Home Assistant taceback/logs

```txt

2022-03-27 20:31:38 ERROR (MainThread) [custom_components.localtuya.common] [525...99c] Connect to 192.168.100.47 failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 155, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

```
## Additional information

I assume it's network related.   But unsure what I'd have to do to get it through the firewall.I'm not fussed if I have to explicitly configure in configuration.yaml and can't discover

**Comment by maxfield-allison** [comment]
in order to make mine pop up I had to use a udp broadcast relay on ports 6667 and 6668 and make sure to allow intervlan traffic in firewall rules. that said, you should be able to define them directly as long as you have nothing blocking.

**Comment by psyciknz** [comment]
Yeah, so I'm not aware of any blocks from the ha network on the lan to the iot network.    But it does seem like something is getting in the way.   What port do these devices listen on (so I can try some curl commands from the various networks)?

**Comment by maxfield-allison** [comment]
You need to have 6667 and 6668 open for UDP. and again, if these devices are announcing via broadcast, then that traffic isnt going to leave the subnet without some assistance from a relay. you should try pinging from one net to the other and if that works then start a relay service and see if they start showing up. certain battery powered devices may also need to be woken up.

**Comment by maxfield-allison** [comment]
if you can ping it then odds are your firewall isnt blocking. and its port 6667 and 6668. again, you'd need a udp relay to get the broadcast traffic used for discovery across the subnet boundary.

**Comment by psyciknz** [comment]
So I may have had something else happening, I started playing with the tuya api directly, and was able to see the device.

Then I had a look at another tool for looking at tuya  and saw the firmware version was 3.3, my config had 3.1....So i management to make a change in the configuration.yaml, and get the device to connect!!

Was just a matter of working through it.  Thanks for your confirmations and help

**Comment by psyciknz** [comment]
Also OMG IT"S SO MUCH FASTER THAN THE OFFICUAL TUYA INTEGRATION!!!

**Comment by maxfield-allison** [comment]
Lol I said the same thing and my wife was like "oh..yea


....


Cool..."

So happy to nerd out with you,

YES!!! I am so stoked at how much faster and more reliable the switches are!!!
