### ISSUE TITLE
After update to HA  2022.06 I get the following "WARNING MESSAGE"

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [rospogrigio/localtuya#845]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 20:46:51 (1 occurrences)
Last logged: 20:46:51

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for localtuya using this method at custom_components/localtuya/__init__.py, line 315: ent_reg = await er.async_get_registry(hass)

**Comment by tankdeer** [comment]
Just came here to post the same issue.

**Comment by golds69** [comment]
I have the same warning message

**Comment by rcblackwell** [comment]
I’m receiving the same error.

**Comment by pergolafabio** [comment]
Pls stop posting "I have the same"...

**Comment by garry0garry** [comment]
https://github.com/home-assistant/core/issues/72951

**Comment by talondnb** [comment]
The same warning, I have.

**Comment by homecb** [comment]
@garry0garry Please remove that link. It's irrelevant. As pointed out, you reported it in the wrong repo.

**Comment by Jaguaza** [comment]
The same warning, I have.

**Comment by zyigo** [comment]
The have, warning, same I.

**Comment by JonasPed** [comment]
This is a duplicate of #830

**Comment by jeremysherriff** [comment]
Fixed in PR #842 please follow that for updates.
