### ISSUE TITLE
Failed to retrieve device list.  Error 1106: permission deny

### ISSUE THREAD

**Issue by bigverm23** [rospogrigio/localtuya#858]
## The problem
Successfully configured a HASS cloud project on iot.tuya.com.  Successfully added the localtuya repository through HACS.  When I attempt to ADD INTEGRATION through HASS, I get the Error 1106 (I have Do not configure a Cloud API account unchecked).

## Environment
- Localtuya version: 4.0.0 
- Last working localtuya version (if known and relevant): not known/relevant
- Home Assistant Core version: 2022.6.5
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [x] Are you using the Tuya App in parallel ? SmartLife

## Provide Home Assistant taceback/logs
022-06-14 06:55:18 ERROR (MainThread) [custom_components.localtuya.config_flow] Cloud API get_devices_list failed: Error 1106: permission deny

**Comment by smithbill17** [comment]
I'm also getting this same issue (see attached LocalTuya integration config page).

I also discovered I had to Authorize my Tuya IoT project for the 'Smart Home Devices Management ' & 'Smart Home Home Management' services, otherwise I got an error saying the integration was not authorized to call an API.
![IMG_20220614_143225](https://user-images.githubusercontent.com/66825587/173590637-73c82b4c-a486-4092-8025-e072bab73978.jpg)

**Comment by n00bcodr** [comment]
You would have to get the user ID from [Tuya IoT Platform](https://iot.tuya.com/) as mentioned in the documentation.

To setup a Tuya IoT Platform account and setup a project in it, refer to the instructions for the official Tuya integration: https://www.home-assistant.io/integrations/tuya/ The place to find the Client ID and Secret is described in this link (in the ["Get Authorization Key"](https://www.home-assistant.io/integrations/tuya/#get-authorization-key) paragraph), while the User ID can be found in the "Link Tuya App Account" subtab within the Cloud project:

![image](https://user-images.githubusercontent.com/49611451/173591101-dde54c68-759f-4179-8d2c-b67ba6c34981.png)

**Comment by smithbill17** [comment]
> You would have to get the user ID from [Tuya IoT Platform](https://iot.tuya.com/) as mentioned in the documentation.
> 
I've already entered my Client ID, Secret & UID as shown in the image I attached (although blanked out for security reasons). I still get the "Error 1106: permission deny"

**Comment by smithbill17** [comment]
Okay - think I've figured out where I went wrong. I have TWO projects (one no longer used as previously the official Tuya integration was configured with a UK datacentre & this didn't work - I had to recreate my project with an EU datacentre). And subsequently, I think the Tuya IoT defaulted to showing me the ClientID & Secret for the older (now defunct) project.

Sorted.

**Comment by smithbill17** [comment]
> The integration does NOT however pick up any already connected devices.

No, you have to then go into Integration Configuration and 'Add a device', but it will automatically retrieve the device ID & Local Key for you (this is as per the instructions)

**Comment by Moehre13** [comment]
I had the Same Issue, my problem where a copied blank space... Please check yours again.

**Comment by bigverm23** [comment]
getting there...at least was able to add the device...

**Comment by mandelshai** [comment]
cant connect to ir

**Comment by dariodoc** [comment]
> the User ID can be found in the "Link Tuya App Account" subtab within the Cloud project:


> I had the same issue. try using the UID rather than your email address.

**Comment by mandelshai** [comment]
Hi dario
 ?can you elaborate more please, do you able to activate  tuya ir through
HASSIO

‫בתאריך יום ה׳, 19 בינו׳ 2023 ב-18:27 מאת ‪Dario Ocampo‬‏ <‪
***@***.***‬‏>:‬

**Comment by sden61** [comment]
> UID

Working!

**Comment by enoversum** [comment]
> I had the Same Issue, my problem where a copied blank space... Please check yours again.

Oh my, I didn#t even think of that, weep weep. Yes, my UID had a BLANK space in the beginning, because I double-clicked it on the Tuya site to copy it. Thank you so much, I would have searched for hours what could be the culprit!
