### ISSUE TITLE
No Option to Delete a Device...

### ISSUE THREAD

**Issue by almighty059** [rospogrigio/localtuya#879]
I see no option to delete a device like I could in the previous versions. I only see the option to remove an entity.

**Comment by patrik-malina** [comment]
Open device. On device info click on 3 dots. Delete device

**Comment by almighty059** [comment]
@patrik-malina thank you and for anyone else here is a screenshot...

![Screenshot 2022-06-15 155026](https://user-images.githubusercontent.com/63380298/173925557-10451f68-d8e1-498b-86db-4d4df675e206.jpg)
.
