### ISSUE TITLE
Lost entity configs

### ISSUE THREAD

**Issue by sciurius** [rospogrigio/localtuya#895]
## The problem

After upgrade to 4.0 some (most? all?) entities get new, default entity ids based on the friendly name, causing everything that used customized IDs to malfunction. This is gross.

Also, since YAML is no longer allowed, having to change all the entity id to the customized values must be done via the UI which is a pain.

**PLEASE** add this to the breaking changes of the release notes so users can reconsider upgrading.

Update: Areas seem to have gone, too.

**Comment by julianjwong** [comment]
Also related to bug
https://github.com/rospogrigio/localtuya/issues/878

I've had the same issues. Going to edit an existing device and then saving will revert the entity names. Mostly impacts Dashboard components which are tied to entity names. I believe automation still works

**Comment by CloCkWeRX** [comment]
The release notes are as follows:
![image](https://user-images.githubusercontent.com/365751/180631487-3a0e03a1-2b45-49b8-a5d9-5237454ab3a4.png)

https://github.com/rospogrigio/localtuya#adding-the-integration explictly mentions the change.
This release got an entire major version number change (3.X to 4.X)

I'm unclear what more you want here.

**Comment by sciurius** [comment]
My v3 configuration was done via UI, not YAML. I guess I misunderstood
> If you upgrade LocalTuya from v3.x.x or older, the config entry will automatically be migrated to the new setup. Everything should work as it did before the upgrade,

**Comment by sciurius** [comment]
Anyway, it's all dealt with and now I'm just a happy localtuya user.
Thanks!
