### ISSUE TITLE
Home Assistant 2022.7: LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by pimw1** [rospogrigio/localtuya#929]
## The problem

Per Home Assistant 2022.7, i receive the following warning. There is no functional impact yet (which makes sense, it will sart breaking in version 2022.10). Local Tuya is making use of a to-be-deprecated mtehod.

```
Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Number (documentation, issues)
First occurred: 21:15:12 (1 occurrences)
Last logged: 21:15:12

custom_components.localtuya.number::LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
```

## Environment

- Localtuya version:  4.0.1
- Last working localtuya version (if known and relevant): 4.0.1
- Home Assistant Core version: 2022.7b2
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Update from Home Assistant 2022.6 to 2022.7 (currently still in beta)
2. check the logs of home assistant after a reboot

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```txt

```

**Comment by vaibhav2912** [comment]
I updated to HA core 2022.7 today and I see the same warning.

```
Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Number (documentation, issues)
First occurred: 10:24:41 PM (1 occurrences)
Last logged: 10:24:41 PM

custom_components.localtuya.number::LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
```

**Comment by smarthomefamilyverrips** [comment]
Will follow here for updates 👍🏻

**Comment by fhornrudd** [comment]
Noticed this is probably preventing changing the temperature units with the new UI in 2022.7 (my tuya temperatures changed from  showing as °F to °C and the entity won’t let me change preference likely due to this number entity being deprecated)

**Comment by smarthomefamilyverrips** [comment]
https://github.com/rospogrigio/localtuya/pull/944

Using the changes in this commit/pull request worked for me. Thanks!

**Comment by DCG81** [comment]
same problem I am facing

Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Number ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 2:20:12 AM (1 occurrences)
Last logged: 2:20:12 AM

custom_components.localtuya.number::LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

suddenly my Local Tuya devices go offline and I need to restart HA to fix it

**Comment by DCG81** [comment]
> #944
> 
> Using the changes in this commit/pull request worked for me. Thanks!

hey how do we do this? pls help

**Comment by smarthomefamilyverrips** [comment]
> > #944
> > Using the changes in this commit/pull request worked for me. Thanks!
> 
> hey how do we do this? pls help

You will need to make the changes manually to yhe number.py file using file editor.

**Comment by DCG81** [comment]
> > > #944
> > > Using the changes in this commit/pull request worked for me. Thanks!
> > 
> > 
> > hey how do we do this? pls help
> 
> You will need to make the changes manually to the custom_components/localtuya/number.py file using file editor.

yes did that and it worked, thanks :)

**Comment by sebaschn** [comment]
> > > #944
> > > Using the changes in this commit/pull request worked for me. Thanks!
> > 
> > 
> > hey how do we do this? pls help
> 
> You will need to make the changes manually to the custom_components/localtuya/number.py file using file editor.

obviously newbie here.
i've read the blog post ( https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/ )
a few times now. but still i have no clue what exactly i have to change.
what (now buggy) code do i have to turn into what new code?
thank you in advance!!

**Comment by ElStupid** [comment]
@sebaschn See https://github.com/rospogrigio/localtuya/pull/944/files for the changes you have to make (red lines are old, green lines are new, blue and white ones unchanged)

Ran into this problem just today

**Comment by sebaschn** [comment]
@ElStupid 
i thank you so much!
i've changed the code - and for now (?) it works!
(just in case, i've left the old code in BUT disabled it with "#" )

**Comment by Yonny24** [comment]
I still have local tuya down even after updating number.py manually. 
Please advise. Thank

2022.8.7

`Logger: homeassistant
Source: custom_components/localtuya/common.py:117
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 9:18:30 PM (108 occurrences)
Last logged: 9:19:05 PM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
    self.device_found(decoded)
  File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
    self._callback(device)
  File "/config/custom_components/localtuya/__init__.py", line 105, in _device_discovered
    entry = async_config_entry_by_device_id(hass, device_id)
  File "/config/custom_components/localtuya/common.py", line 117, in async_config_entry_by_device_id
    if device_id in entry.data[CONF_DEVICES]:
KeyError: 'devices'`

**Comment by CloCkWeRX** [comment]
Now closable

**Comment by pimw1** [comment]
#944 fixed the isssue. Thanks for all the help!
