### ISSUE TITLE
LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by AdmiralStipe** [rospogrigio/localtuya#939]
## The problem
After updating to HA 2022.7 I get this warning in my log at every restart: 
`2022-07-07 11:45:54 WARNING (MainThread) [homeassistant.components.number] custom_components.localtuya.number::LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.`
## Environment
- Localtuya version: 4.0.1
- Home Assistant Core version: 2022.7 Supervised

**Comment by PFly61** [comment]
Same problem for the Beca BHT-6000 Thermostat which is no longer available

**Comment by pimw1** [comment]
Hi, there is already an issue open for this: https://github.com/rospogrigio/localtuya/issues/929
Kindly close your issue and converge all info in the existing issue.
