### ISSUE TITLE
Registering localtuya as default component in HACS

### ISSUE THREAD

**Issue by rospogrigio** [rospogrigio/localtuya#96]
@postlund I am trying to register localtuya as a HACS default component but I am having difficulties with which you can help me out. Some automatic checks are failing:
1) I needed to create this PR: https://github.com/home-assistant/wheels-custom-integrations/pull/161 but a check fails. I believe it wants some kind of requirement about the python version to be stated in the manifest.json , do you know what we should add and where?
2) the PR for HACS is https://github.com/hacs/default/pull/662 . Apart from the wheels failure above, I get the following error in one of the checks:
```
::INFO:: Category: integration
::INFO:: Repository: rospogrigio/localtuya-homeassistant
Error:  ::error:: No hacs.json file in the root of the repository.
```
But hacs.json is actually present in the root... why is it not being detected? should it be copied also within custom_components/localtuya ?

Thank you for your help

**Comment by rospogrigio** [comment]
In the meantime I received suggestions and part 1 is fixed, now let's see if I can fix part 2...

**Comment by rospogrigio** [comment]
@postlund , the main issue now seems to be the fact that in manifest we are calling it localtuya, while the repo is named localtuya-homeassistant, and I have been suggested to rename the repo, which I like (I always felt useless the "-homeassistant" suffix). 
Do you see any issues? Shall I proceed?

**Comment by postlund** [comment]
@rospogrigio 

![](https://memegenerator.net/img/instances/60023518.jpg)

**Comment by postlund** [comment]
You should also update `domains` in hacs.json as it's not correct.

**Comment by carlosvroque** [comment]
Today I decided to migrate my tuya devices over to this component and it seems my timing was spot on. I added the repository to HACS, installed the latest release, restarted and it doesn't show up in the integrations page. 

So I found this issue and it's just bad timing, I'll wait for the next release.

In case it helps here are some errors I got:

> Logger: custom_components.hacs.repository.integration.rospogrigio.localtuya-homeassistant
> Source: custom_components/hacs/repositories/integration.py:88
> Integration: HACS (documentation, issues)
> First occurred: 15:53:43 (1 occurrences)
> Last logged: 15:53:43
> 
> No file found 'manifest.json'

> Logger: custom_components.hacs.repository.integration.rospogrigio.localtuya-homeassistant
> Source: custom_components/hacs/helpers/classes/repository.py:397
> Integration: HACS (documentation, issues)
> First occurred: 15:53:43 (1 occurrences)
> Last logged: 15:53:43
> 
> Missing domain

I also can't uninstal:

> Logger: custom_components.hacs.api.repository
> Source: custom_components/hacs/api/hacs_repository.py:108
> Integration: HACS (documentation, issues)
> First occurred: 15:53:43 (1 occurrences)
> Last logged: 15:53:43
> 
> Could not uninstall

**Comment by rospogrigio** [comment]
Guys, please everybody stick to 3.0.1 until further notice, thank you.

**Comment by postlund** [comment]
PR is merged to HACS now, so you should wave the magical wand now
@rospogrigio 🪄

**Comment by rospogrigio** [comment]
Yes, I was able to skip the bullet... so @postlund what are we supposed to do? I can't remember what was wrong with 3.0.3... should I fix something before deploying the new release?

**Comment by postlund** [comment]
@rospogrigio I was hoping you knew 🤣

**Comment by rospogrigio** [comment]
Oh man... ok, let's try to push a release and see how it goes 🤞

**Comment by pergolafabio** [comment]
with 3.0.3 i was not able to use these extra lines : 

```
        color: 24 # Optional, usually 5 (RGB_HSV) or 24(HSV), default: "none"
        brightness_lower: 29 # Optional, usually 0 or 29, default: 29
        brightness_upper: 1000 # Optional, usually 255 or 1000, default: 1000
        color_temp_min_kelvin: 2700 # Optional, default: 2700
        color_temp_max_kelvin: 6500 # Optional, default: 6500  
```

**Comment by rospogrigio** [comment]
I just published the new release 3.1.0, try it and see if it fixes.

**Comment by dereitz** [comment]
I just installed 3.1.0 today and the LocalTuya integration is not available under Configuration -> Integrations -> +Add Integration.  Any tips would be appreciated!

**Comment by postlund** [comment]
Try to clear your cache/force update. That usually help.

**Comment by dereitz** [comment]
Thanks.  I feel foolish now b/c a Ctrl-F5 did appear to work.  My apologies and thanks for the help!

**Comment by rospogrigio** [comment]
Closing this Issue since localtuya is now registered in HACS.
