### ISSUE TITLE
Is the project not being updated anymore?

### ISSUE THREAD

**Issue by dantetekanem** [rospogrigio/localtuya#988]
I can see several pull requests, some of them can fix the new problems introduced by HAOS 8.4.

If the project is not being updated anymore, there's any other repo or any other way to update the code outside this one?

**Comment by Phoenix260** [comment]
I started using https://github.com/make-all/tuya-local

It works much better but not all devices can be added. Developer is more active though.

**Comment by rospogrigio** [comment]
> I can see several pull requests, some of them can fix the new problems introduced by HAOS 8.4.

I was on vacation. I am still on 8.1, can you point me to the PRs that fix these 8.4 problems?  Thank you

**Comment by dantetekanem** [comment]
@rospogrigio https://github.com/rospogrigio/localtuya/pull/956 looks very promising. And there's also the need to support python 3.9 (I think). Thank you!
