### ISSUE TITLE
Connection to device succeeded but no datapoints found

### ISSUE THREAD

**Issue by gt-levkan2002** [rospogrigio/localtuya#989]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/105607530/184528720-76b951c6-12fd-440e-bcad-f0ecadf15264.png">

Unable to add Tuya zigbee gateway

**Comment by PedroNZ** [comment]
same problem here

**Comment by hbaizer** [comment]
same problem here

**Comment by rospogrigio** [comment]
Zigbee gateway is still not supported, sorry.

**Comment by pickonedev** [comment]
Same issue for wifi devices...
