### ISSUE TITLE
Can't remove device

### ISSUE THREAD

**Issue by JampireX** [rospogrigio/localtuya#995]
When I trying to remove device unchecking entities in **Edit window** I get an unknown error

![image](https://user-images.githubusercontent.com/24954035/186021679-17b7c430-b26e-4161-8246-ed8800a1143a.png)
![image](https://user-images.githubusercontent.com/24954035/186021413-cbb9d4a6-f23d-4f47-b68c-400fdf18722e.png)

**Comment by SeanPaulE** [comment]
I’m having this issue too. ^ Same steps to repeat and same error.

**Comment by SeanPaulE** [comment]
I found the way around this but not using the integration… (maybe it should be an option, or at least documented)

- Find the device in home assistant
- Bring up the overview page (with the Device Info, Controls etc)
- Select the 3 dots under Device Info
- Delete Device

![B35BE937-35A8-4B36-A3CB-2D58A62793DF](https://user-images.githubusercontent.com/16464159/187050672-8cff6d54-be44-4fbf-8597-ccc52b6b9703.jpeg)

This way it can be added again from scratch.

**Comment by rospogrigio** [comment]
Yes, this is the way you are supposed to delete devices. You cannot just delete all the entities from a device.
