### ISSUE TITLE
no Local Tuya in integrations to be added

### ISSUE THREAD

**Issue by Kedryn** [rospogrigio/localtuya#999]
i've added Local Tuya via HACS, but then when i go to integrations and try to add IT, there is no Local Tuya to add.
2022.8.4 HA here.

**Comment by besiktas97** [comment]
Did you try to restart HA, after you have installed local tuya?

**Comment by Kedryn** [comment]
> Did you try to restart HA, after you have installed local tuya?

sure, several times.
But today i noticed i had localtuya in my integrations.
